FlowiseAI/Flowise

packages/components/nodes/documentloaders/Cheerio/Cheerio.ts, packages/components/nodes/documentloaders/Cheerio/cheerio.svg, packages/components/package.json
=> add cheerio web scraper

packages/components/nodes/llms/HuggingFaceInference/HuggingFaceInference.ts
=> Feature/Update HF node

packages/components/nodes/documentloaders/Json/Json.ts, packages/components/nodes/documentloaders/Json/json.svg
=> add JSON loader

packages/components/nodes/vectorstores/Supabase_Existing/Supabase_Exisiting.ts, packages/components/nodes/vectorstores/Supabase_Existing/supabase.svg, packages/components/nodes/vectorstores/Supabase_Upsert/Supabase_Upsert.ts, packages/components/nodes/vectorstores/Supabase_Upsert/supabase.svg, packages/components/package.json
Result Upsert
Result Load Existing Index
=> add supabase upsert

packages/server/src/Interface.ts, packages/server/src/entity/ChatFlow.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts, packages/ui/src/api/apikey.js, packages/ui/src/api/prediction.js, packages/ui/src/menu-items/dashboard.js, packages/ui/src/routes/MainRoutes.js, packages/ui/src/ui-component/dialog/APICodeDialog.js, packages/ui/src/views/apikey/APIKeyDialog.js, packages/ui/src/views/apikey/index.js, packages/ui/src/views/canvas/CanvasHeader.js
Add Authroization API keys
https://user-images.githubusercontent.com/26460777/235314955-3abab42a-a86a-42a6-9686-2218cc835a49.mp4
=> Feature/Add API authorization

packages/components/nodes/vectorstores/InMemory/InMemoryVectorStore.ts, packages/components/nodes/vectorstores/InMemory/memory.svg
Note: `fromExistingIndex` is not working atm
=> Feature/add in-memory vector store

packages/server/src/utils/index.ts
=> fix typo in utils/index.ts

packages/components/nodes/vectorstores/Chroma_Upsert/Chroma_Upsert.ts, packages/components/nodes/vectorstores/InMemory/InMemoryVectorStore.ts, packages/components/nodes/vectorstores/Pinecone_Upsert/Pinecone_Upsert.ts, packages/components/nodes/vectorstores/Supabase_Upsert/Supabase_Upsert.ts, packages/components/nodes/vectorstores/Weaviate_Upsert/Weaviate_Upsert.ts
=> Bugfix/VectorStore Empty Docs

.gitignore, packages/components/nodes/documentloaders/Csv/Csv.ts, packages/components/nodes/documentloaders/Docx/Docx.ts, packages/components/nodes/documentloaders/Json/Json.ts, packages/components/nodes/documentloaders/Pdf/Pdf.ts, packages/components/nodes/documentloaders/Text/Text.ts, packages/components/src/utils.ts, packages/server/package.json, packages/server/src/ChatflowPool.ts, packages/server/src/Interface.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts, packages/ui/src/api/config.js, packages/ui/src/ui-component/checkbox/Checkbox.js, packages/ui/src/ui-component/dialog/APICodeDialog.js, packages/ui/src/ui-component/file/File.js, packages/ui/src/ui-component/table/Table.js, packages/ui/src/utils/genericHelper.js
https://user-images.githubusercontent.com/26460777/236287654-85b6869e-93f0-4ace-b843-12252cd0a9a5.mp4
Add ability to override existing config set on the flow using API
=> Feature/Add API Config

packages/components/nodes/textsplitters/TokenTextSplitter/TokenTextSplitter.ts, packages/components/nodes/textsplitters/TokenTextSplitter/tiktoken.svg, packages/components/package.json
=> add token text splitter

packages/components/nodes/textsplitters/CharacterTextSplitter/CharacterTextSplitter.ts, packages/components/nodes/textsplitters/CharacterTextSplitter/textsplitter.svg
=> add character text splitter

packages/ui/src/views/canvas/CanvasHeader.js
=> fixed bug: chatflow name is being replaced by old name

packages/components/nodes/tools/WebBrowser/WebBrowser.ts, packages/components/nodes/tools/WebBrowser/webBrowser.svg, packages/server/marketplaces/WebBrowser.json
=> Feature/Add WebBrowserTool

packages/ui/src/ui-component/cards/ItemCard.js
**Issue**
Cards in marketplace were not showing the complete text and images.
**How it looked before**
**How it looks now**
=> marketplace cards text and images overflow fixed

packages/components/nodes/agents/AutoGPT/AutoGPT.ts, packages/components/nodes/agents/BabyAGI/BabyAGI.ts, packages/components/nodes/agents/BabyAGI/core.ts, packages/components/nodes/agents/MRKLAgentLLM/MRKLAgentLLM.ts, packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts, packages/components/nodes/chains/RetrievalQAChain/RetrievalQAChain.ts, packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts, packages/server/marketplaces/Conversational Retrieval QA Chain.json, packages/server/marketplaces/Github Repo QnA.json, packages/server/marketplaces/MRKLAgent.json, packages/server/marketplaces/Metadata Filter Load.json, packages/server/marketplaces/Metadata Filter Upsert.json, packages/server/marketplaces/Multiple VectorDB.json, packages/server/marketplaces/SQL DB Chain.json, packages/server/marketplaces/Zapier NLA.json
Previously only OpenAI Completion Model is allowed to connect to certain chains/agents.
It is now possible for ChatGPT as well:
=> Feature/Add BaseLanguageModel

packages/components/nodes/tools/RequestsGet/RequestsGet.ts, packages/components/nodes/tools/RequestsPost/RequestsPost.ts
Adding `maxLengthOutput` and `headers`:
Related issue: https://github.com/FlowiseAI/Flowise/issues/132
=> Feature/Requests Tools

packages/components/nodes/chatmodels/ChatLocalAI/ChatLocalAI.ts
=> Bugfix/Add BaseChatModel class to LocalAI

packages/ui/src/ui-component/dialog/APICodeDialog.js
https://github.com/FlowiseAI/Flowise/assets/26460777/a3863b28-5fea-424e-87bf-808df97deabf
=> Feature/Embed Chat Customization

packages/server/src/utils/index.ts
disable stream when in child mode
=> Bugfix/Disable Stream For ChildMode

packages/server/src/index.ts
Fix first chat message not found from API call
=> Bugfix/First Message Not Found

packages/ui/src/ui-component/dialog/APICodeDialog.js
add fontsize and chatflowconfig customization
=> Feature/EmbedChat Customization

packages/ui/src/ui-component/input/Input.js, packages/ui/src/views/canvas/NodeInputHandler.js
should fix this - https://github.com/FlowiseAI/Flowise/issues/389
=> Bugfix/Input Number

packages/components/nodes/prompts/PromptTemplate/PromptTemplate.ts
=> remove returnJSONStr function

packages/server/.env.example, packages/server/src/Interface.ts, packages/server/src/entity/ChatFlow.ts, packages/server/src/entity/ChatMessage.ts, packages/server/src/entity/Tool.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts, packages/ui/src/api/chatflows.js, packages/ui/src/views/canvas/CanvasHeader.js, packages/ui/src/views/canvas/index.js, packages/ui/src/views/chatbot/index.js, packages/ui/src/views/chatflows/APICodeDialog.js, packages/ui/src/views/chatflows/ShareChatbot.js
- Fields saved for each chatbot is not retrieved again correctly, they are displayed as empty, however the link still shows the chatbot accordenly to the modified-saved fields, colors, etc....
- Shared link just runs fine with the same browser (Chrome in my case) where I have Flowise session open. If I try it with another web-browsr like Edge, I just see this message "Invalid Chatbot".
- new env variable APIKEY_PATH to specify where api key is saved
=> Bugfix/Share Chatbot

packages/components/nodes/chatmodels/ChatHuggingFace/ChatHuggingFace.ts, packages/components/nodes/chatmodels/ChatHuggingFace/core.ts, packages/components/nodes/embeddings/HuggingFaceInferenceEmbedding/HuggingFaceInferenceEmbedding.ts, packages/components/nodes/embeddings/HuggingFaceInferenceEmbedding/core.ts, packages/components/nodes/llms/HuggingFaceInference/HuggingFaceInference.ts, packages/components/nodes/llms/HuggingFaceInference/core.ts, packages/components/package.json, packages/components/src/utils.ts
=> Feature/Add endpoint to HF

packages/components/nodes/tools/ChainTool/ChainTool.ts, packages/components/nodes/tools/ChainTool/core.ts
Bug: Current ChainTool doesn't work with LLMChain:
Add fix to allow chaintool with llmchain
=> Bugfix/ChainTool with LLMChain

packages/components/nodes/memory/MotorheadMemory/MotorheadMemory.ts, packages/components/nodes/memory/MotorheadMemory/memory.svg
#368
https://github.com/FlowiseAI/Flowise/issues/368#issuecomment-1623036178
=> Feature/Motorhead Memory

packages/components/src/utils.ts
Results:
**[itsjane text/xml sitemap](https://www.itsjane.com/sitemap.xml)**
**[wagslane application/xml sitemap](https://wagslane.dev/sitemap.xml)**
**[wagslane html](https://wagslane.dev/posts/college-a-solution-in-search-of-a-problem/)**
=> add content type text/xml

packages/ui/src/ui-component/input/Input.js
this the second pull request, the pull request just change the value type. this is my the first pull request( •̀ ω •́ )✧，thank you.
=> fix: bug inputType

packages/components/nodes/embeddings/HuggingFaceInferenceEmbedding/core.ts
Bug: HFEmbeddings is giving `featureExtraction` is not a function
=> Bugfix/HF Embeddings

packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts, packages/components/nodes/chains/ConversationalRetrievalQAChain/prompts.ts
Bug: current system message doesnt work for different chain types
=> Bugfix/SystemMessage For Different Chain Type

packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts, packages/components/nodes/chains/ConversationalRetrievalQAChain/prompts.ts, packages/server/marketplaces/chatflows/Conversational Retrieval QA Chain.json, packages/server/src/ChildProcess.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts, packages/ui/src/views/canvas/CanvasHeader.js, packages/ui/src/views/chatbot/index.js, packages/ui/src/views/chatflows/APICodeDialog.js, packages/ui/src/views/chatflows/ShareChatbot.js
- add refine chain type custom system message
- allow all memory type to conver_re_qa_chain
- fix startsWith undefined where override config file is not passed
- ability to generate new session id when sharing chatbot
=> Bugfix/StartsWith Undefined

packages/server/nodemon.json
add the components change to the server nodemon watch, that if we change the components files, the components will tsc and the server will restart to load the new change components.
=> Fix: server watch

packages/components/nodes/chains/ConversationChain/ConversationChain.ts
**Before**:
**After:**
Issue #606
=> remove curly bracket in loaded document text

packages/server/src/ChildProcess.ts
=> Fix typo in ChildProcess.ts

CONTRIBUTING.md
=> Update CONTRIBUTING.md fix DATABASE_USER(NAME)

packages/components/nodes/chains/LLMChain/LLMChain.ts, packages/components/nodes/memory/DynamoDb/DynamoDb.ts, packages/components/nodes/memory/MotorheadMemory/MotorheadMemory.ts, packages/components/nodes/memory/RedisBackedChatMemory/RedisBackedChatMemory.ts, packages/components/nodes/memory/ZepMemory/ZepMemory.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts
Prompt Chaining wasn't taking in previous response:
After fix:
=> Bugfix/Prompt Chaining

packages/server/src/Interface.ts, packages/server/src/utils/index.ts, packages/ui/src/ui-component/table/Table.js, packages/ui/src/views/chatflows/APICodeDialog.js
=> Feature/Multi Config

packages/ui/src/utils/genericHelper.js, packages/ui/src/views/chatmessage/ChatMessage.js
[Enhancement #329](https://github.com/FlowiseAI/Flowise/discussions/329)
[FlowiseChatEmbed PR #24](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/24)
Result:
=> add hyperlink

packages/server/src/ChildProcess.ts, packages/server/src/index.ts
add appdatasource and databaseEntities to run method
=> Bufgix/GetRepository Undefined for Agent

packages/components/nodes/tools/CustomTool/CustomTool.ts, packages/ui/src/views/tools/ToolDialog.js
https://docs.flowiseai.com/tools/custom-tool#override-function-from-api
=> Feature/OverrideConfig CustomToolFunc

CODE_OF_CONDUCT-ZH.md
=> fix md file format error

packages/components/nodes/vectorstores/Vectara_Upsert/Vectara_Upsert.ts
=> fix vectara upsert naming

packages/components/nodes/vectorstores/Vectara_Existing/Vectara_Existing.ts, packages/components/nodes/vectorstores/Vectara_Upsert/Vectara_Upsert.ts
This PR fixes the Vectara metadata filter type
=> Fix Vectara filter

packages/components/nodes/agents/ConversationalRetrievalAgent/ConversationalRetrievalAgent.ts
fix conversation retrieval qa agent original prompt
=> Feature/ConversationaRetrievalQAAgent System Message

packages/components/nodes/documentloaders/Cheerio/Cheerio.ts, packages/components/nodes/documentloaders/Playwright/Playwright.ts, packages/components/nodes/documentloaders/Puppeteer/Puppeteer.ts, packages/server/marketplaces/chatflows/WebPage QnA.json
Puppeteer & Playwright takes additional configs to load the data from webpages.
=> Puppeteer & Playwright additional config options

packages/server/src/index.ts, packages/ui/src/ui-component/dialog/AboutDialog.js
=> Feature/UI Current Version

packages/components/nodes/agents/AutoGPT/AutoGPT.ts, packages/server/src/utils/index.ts
=> Feature/Update Autogpt

packages/components/src/utils.ts
Closes/Related: (https://github.com/FlowiseAI/Flowise/issues/839)
=> fix: unknown error throwing on missing credentials. error handling improves on ui section

packages/components/credentials/ConfluenceApi.credential.ts
[Discord]Aaron Davis: How to get the confluence document loader to work?
Add https://id.atlassian.com/manage-profile/security/api-tokens
=> swap URL to get Confluence access token directly

packages/components/nodes/embeddings/GoogleVertexAIEmbedding/GoogleVertexAIEmbedding.ts
Adaptation of [multi-lingual support of Vertex AI Embedding](https://github.com/Yongtae723/Flowise/pull/new/fix/add_new_model_embedding_vertexai), which is published Google Could Next on last week! 🎉
=> Add input option for Model Name in GoogleVertexAIEmbedding

packages/components/nodes/chatmodels/ChatGooglePaLM/ChatGooglePaLM.ts, packages/components/nodes/chatmodels/ChatGooglePaLM/Google_PaLM_Logo.svg, packages/components/nodes/embeddings/GooglePaLMEmbedding/GooglePaLMEmbedding.ts, packages/components/nodes/embeddings/GooglePaLMEmbedding/Google_PaLM_Logo.svg
This is a follow-on from the recently accepted PaLM API LLM component (#882).
=> PaLM API Chat and Embedding components

packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
Added options: includesTables, ignoreTables, sampleRowsInTableInfo and topK to sqldb chain
=> Added some options for SqlDatabaseChain

packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts, packages/server/marketplaces/chatflows/SQL DB Chain.json
Both include tables & ignore tables can't be used together
=> Bugfix/SQLDBChain IncludeTables & IgnoreTables

packages/components/nodes/documentloaders/PlainText/PlainText.ts, packages/components/nodes/documentloaders/PlainText/plaintext.svg
=> Feature/PlainText DocLoader

README.md
=> feat: Adding Elestio as deployment option

packages/components/nodes/vectorstores/Vectara/Vectara_Existing.ts, packages/components/nodes/vectorstores/Vectara/Vectara_Upload.ts, packages/components/nodes/vectorstores/Vectara/Vectara_Upsert.ts, packages/server/marketplaces/chatflows/Vectara LLM Chain Upload.json
minor update to labels
Upd 'source' in Vectara constructor
=> Minor update to Vectara modules

packages/components/nodes/cache/InMemoryCache/InMemoryEmbeddingCache.ts
=> Feature/Add InMem cache embeddings

packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts, packages/server/src/Interface.ts, packages/server/src/database/entities/ChatMessage.ts, packages/server/src/database/migrations/mysql/1700271021237-AddFileAnnotationsToChatMessage.ts, packages/server/src/database/migrations/mysql/index.ts, packages/server/src/database/migrations/postgres/1699481607341-AddUsedToolsToChatMessage.ts, packages/server/src/database/migrations/postgres/1700271021237-AddFileAnnotationsToChatMessage.ts, packages/server/src/database/migrations/postgres/index.ts, packages/server/src/database/migrations/sqlite/1700271021237-AddFileAnnotationsToChatMessage.ts, packages/server/src/database/migrations/sqlite/index.ts, packages/server/src/index.ts, packages/ui/src/api/assistants.js, packages/ui/src/ui-component/dialog/ViewMessagesDialog.js, packages/ui/src/views/assistants/AssistantDialog.js, packages/ui/src/views/assistants/DeleteConfirmDialog.js, packages/ui/src/views/chatmessage/ChatMessage.js
Linked Embedded Chat [PR](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/53)
=> Feature/Add file annotations, sync and delete assistant

packages/server/src/index.ts, packages/ui/src/views/apikey/index.js
This PR updates the API Keys Screen to show the number of chatflows associated with each key and allows the user to view the flow details. The warning message is also updated to ensure that the user does not accidentally delete the key.
=> UX Changes to the API Keys Screens

packages/ui/src/ui-component/table/FlowListTable.js
=> Bugfix: UI Fix - left align long chat flow names for consistency.

packages/components/credentials/RedisCacheApi.credential.ts, packages/components/nodes/cache/RedisCache/RedisCache.ts, packages/components/nodes/cache/RedisCache/RedisEmbeddingsCache.ts, packages/components/nodes/memory/RedisBackedChatMemory/RedisBackedChatMemory.ts
This is needed for example connecting to the azure redis sever.
=> Added boolean flag which enables ssl connection for redis nodes.

packages/components/src/utils.ts, packages/server/src/utils/index.ts
update default location for encryption key
=> Bugfix/Credential Decrypt

packages/ui/src/ui-component/dialog/PromptLangsmithHubDialog.js
This fix loads the prompts on dialog open.
=> Bugfix: Unncessary load of Prompts on chatflow open. 

packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts, packages/server/marketplaces/chatflows/OpenAI Assistant.json
- Added input moderation to assistant
- Prevent app from crashing by using try catch
=> Feature/OpenAI Assistant Update

packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts
avoid submitting tool outputs when in_progress
=> Feature/OpenAI Assistant

packages/components/nodes/moderation/SimplePromptModeration/SimplePromptModeration.ts, packages/components/nodes/moderation/SimplePromptModeration/SimplePromptModerationRunner.ts
added LLM to moderation to detect similar deny sentences
=> Feature/LLM Moderation

packages/components/nodes/utilities/CustomFunction/CustomFunction.ts, packages/server/src/utils/index.ts, packages/ui/src/ui-component/dialog/ExpandTextDialog.js
add fix for passing json variable
=> Bugfix/Pass Json Variable Value

packages/components/nodes/agents/OpenAIFunctionAgent/OpenAIFunctionAgent.ts
refer to https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/format_scratchpad/openai_functions.py#L29
and fix the role of systemMessage from `ai` to `system`.
=> Fix OpenAIFunctionAgent that function not return string result

packages/components/nodes/chatmodels/ChatGoogleGenerativeAI/ChatGoogleGenerativeAI.ts, packages/components/package.json, packages/components/src/utils.ts
Added `Harm Category` and `Harm Block Threshold` selection
Enhancement of #1520
=> add TopK and safetySettings into Google Gemini

.github/workflows/autoSyncMergedPullRequest.yml, .github/workflows/autoSyncSingleCommit.yml
=> Add autoSync github workflows

packages/components/nodes/tools/CustomTool/CustomTool.ts, packages/components/nodes/tools/CustomTool/core.ts, packages/components/nodes/utilities/CustomFunction/CustomFunction.ts, packages/components/nodes/utilities/IfElseFunction/IfElseFunction.ts, packages/components/src/Interface.ts, packages/components/src/utils.ts, packages/server/src/index.ts, packages/server/src/utils/index.ts
=> Feature/add $vars and $flow to custom function

packages/components/nodes/chains/ConversationChain/ConversationChain.ts, packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts, packages/server/marketplaces/chatflows/Claude LLM.json, packages/server/marketplaces/chatflows/Simple Conversation Chain.json
- add verbose (console callback manager) to chains
- updated conversation chain to have ability to use chatprompt template
=> Feature/Add Verbose to Chains

packages/server/src/index.ts
Some users would like to have more info from API response:
=> Feature/Update Return Response

packages/server/src/index.ts
Return the chat message id in the api response.
=> feature : include chat message id in result

packages/components/nodes/vectorstores/Qdrant/Qdrant.ts, packages/components/nodes/vectorstores/Qdrant/Qdrant_Existing.ts
=> Bugfix/Qdrant Filter

packages/components/nodes/memory/MongoDBMemory/MongoDBMemory.ts
https://github.com/FlowiseAI/Flowise/issues/1622
Using a singleton class for mongodb to prevent connections mismanagement.
=> Mongodb for Chat history #1622

packages/components/nodes/cache/RedisCache/RedisCache.ts
This fixes https://github.com/FlowiseAI/Flowise/issues/1589
=> Bugfix/Switching Redis TTL from EX to PX to match TTL in milliseconds

packages/components/nodes/chains/ConversationChain/ConversationChain.ts, packages/server/marketplaces/chatflows/Claude LLM.json, packages/server/marketplaces/chatflows/Simple Conversation Chain.json
=> Feature/Conversation Chain Input Moderation

packages/components/nodes/documentloaders/Folder/Folder.ts
Recursive loading wasn't implemented for folder loader.
This PR fixes this issue.
=> add recursive option for folder-loader

packages/server/src/index.ts
This should fix #1881 by solving the sorting.
=> Fix for 1881 sorting for Flowise QnA

packages/server/src/database/migrations/postgres/1707213601923-AddFeedback.ts
Former pk were used in AddVariables migration file
=> Primary Key name must be unique

packages/components/nodes/tools/CustomTool/CustomTool.ts
https://docs.flowiseai.com/integrations/langchain/tools/custom-tool#override-custom-tool
=> Feature/Custom Tool OverrideConfig

packages/components/nodes/memory/DynamoDb/DynamoDb.ts
=> bugfix: Dynamo Memory - messageAttributeName

packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI_LlamaIndex.ts, packages/components/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding_LlamaIndex.ts
Add BasePath parameter setting support to ChatOpenAI LlamaIndex
=> Feature: Add BasePath parameter setting support to ChatOpenAI LlamaIndex

packages/components/credentials/models.json
This PR needs to be revised and merged before https://github.com/FlowiseAI/Flowise/pull/2113.
=> Addition of model.json to externalize model-lists and related key-values

packages/components/nodes/recordmanager/MySQLRecordManager/MySQLrecordManager.ts
=> Bugfix/MySQL RecordManager Varchar Size

README-JA.md, README-ZH.md
I created Japanese translated README.
=> Add Japanese README

packages/components/nodes/embeddings/AWSBedrockEmbedding/AWSBedrockEmbedding.ts
**Description:** 
- Added missing requirements for bedrock cohere embed model. 
- Split functions to support needs for titan models.
- Added options for input type with validation check.
Issues this addresses: #2060
=> Added bedrock cohere embed model requirements

.github/workflows/main.yml, package.json, packages/components/nodes/vectorstores/Supabase/Supabase.ts, packages/components/nodes/vectorstores/Supabase/Supabase_Upsert.ts
When upserting records, the ids are empty, causing following error:
Fix: added id to the index records
=> Bugfix/Supabase Upserting

packages/components/models.json
=> added llama 3 models to bedrock

README-JA.md, README-KR.md, README-ZH.md, README.md
I added Korean translation for Korean developers. I would be good starting point for Korean contributors.
=> Add Korean translation in README.md file

packages/ui/src/store/constant.js, packages/ui/vite.config.js
This PR removes hard code backend port and automatically reads the port from server's env file.
=> feat(ui): auto proxy backend

packages/ui/src/views/canvas/index.jsx
- add cloned nodes to avoid mutation on original nodes
=> Bugfix/Sync Nodes

packages/ui/vite.config.js
closes https://github.com/FlowiseAI/Flowise/pull/2238#discussion_r1586562756
=> Fix streaming not work

.gitignore
Update gitignore to never commit secrets or vscode configs
=> Ignore keys and other secrets

packages/components/src/modelLoader.ts
fallback to fetch local models json file
=> Bugfix/Local Models Json

packages/server/package.json, packages/server/test/utils/validateKey.test.ts
Add some unit tests for src/utiles/validateKey
To run the test:
go to /server, do `pnpm test`
#1220
=> test validateKey

CONTRIBUTING.md, packages/components/src/handler.ts
Added: environment var LOG_JSON_SPACES with default value 2. Used to no beautify JSON on handler.ts
Fix: logger.verbose was not working because default log level was info
Updated: CONTRIBUITING.md
=> Added LOG_JSON_SPACES to control json beautify

packages/server/src/utils/index.ts
This PR fixes that #2461 cannot handle newline(`\r\n`) on windows.
=> Fix JSON escaping (better)

packages/components/nodes/vectorstores/OpenSearch/OpenSearch.ts
Fixes https://github.com/FlowiseAI/Flowise/issues/2544
=> Fix OpenSearch vector store upsert

packages/server/src/services/documentstore/index.ts
fixes https://github.com/FlowiseAI/Flowise/issues/2517
=> adding a document loader returns the correct id

packages/ui/src/views/chatflows/EmbedChat.jsx
HTML Embed Chat popup configuration updated based on the latest release of flowise-embed@1.3.2
=> HTML Embed Chat popup configuration updated

packages/server/marketplaces/agentflows/Prompt Engineering Team.json
This is the Agentflow template, a Prompt Engineering Team, presented here https://github.com/FlowiseAI/Flowise/discussions/2571
=> Adding Agentflow Template

packages/components/nodes/tools/ChatflowTool/ChatflowTool.ts, packages/server/src/utils/buildChatflow.ts
Fixes #2584 
_Discussion is ongoing in the issue, but I feel this change is good enough while we evaluate if it's needed to change the whole approach._
=> Bugfix - Add x-forwarded-proto as source for http protocol for base url and add base url field to ChatflowTool

packages/components/nodes/tools/Searxng/SearXNG.svg, packages/components/nodes/tools/Searxng/Searxng.ts
A first searxng implementation for the tools
=> Searxng Tool implementation

packages/server/src/services/documentstore/index.ts
fixes https://github.com/FlowiseAI/Flowise/issues/2618
=> fix totalChars accumulator for undefined pageContent

packages/server/src/controllers/chatflows/index.ts, packages/server/src/services/chatflows/index.ts, packages/server/src/utils/apiKey.ts
This PR fixes apikey not URL safe(which make url routing not work). and add keyonly filtering the chatflows.
=> Fix apikey not URL safe

packages/components/nodes/vectorstores/Postgres/Postgres.ts
Verified working correctly:
1.) Set filter:
2.) Retrieve correctly
=> Feature/Add filter to Postgres VectorStore

packages/components/src/multiModalUtils.ts, packages/server/src/utils/buildChatflow.ts
=> Feature/Add ability to upload image url when calling API

packages/components/models.json, packages/components/nodes/retrievers/VoyageAIRetriever/VoyageAIRerankRetriever.ts
- Embedding Models: https://docs.voyageai.com/docs/embeddings#model-choices
- Rerank Models: https://docs.voyageai.com/docs/reranker#model-specifics
=> update: VoyageAI Models

packages/ui/src/views/chatflows/EmbedChat.jsx
This PR adds new feature of send and receive message sound and show Agent Messages functionality in embed chat.
=> Embed chat configuration updated

packages/ui/src/ui-component/table/ToolsListTable.jsx, packages/ui/src/views/tools/index.jsx
=> Add table view to tools page

packages/components/nodes/sequentialagents/Agent/Agent.ts, packages/components/nodes/sequentialagents/LLMNode/LLMNode.ts, packages/components/nodes/sequentialagents/State/State.ts, packages/components/nodes/sequentialagents/ToolNode/ToolNode.ts
```
{
"question": "hello",
"overrideConfig": {
"stateMemory": [
{
"Key": "somekey",
"Operation": "Replace",
"Default Value": "somevalue"
}
]
}
}
```
=> Feat/add ability to specify initial state in overrideConfig

CONTRIBUTING.md, docker/.env.example, i18n/CONTRIBUTING-ZH.md, packages/components/src/Interface.ts, packages/server/.env.example, packages/server/src/AppConfig.ts, packages/server/src/NodesPool.ts, packages/server/src/commands/start.ts, packages/ui/src/views/canvas/AddNodes.jsx
- add a new flag: `SHOW_COMMUNITY_NODES`, when set to true, will display nodes created by community
- community node is differentiated by the `author`. For instance, if a node has the `author` specified, it is a community node
```
class SomeNode implements INode {
...
author: string
constructor() {
....
this.author= 'Some User'
}
}
```
=> Feature/Community Node

packages/components/nodes/sequentialagents/Agent/Agent.ts, packages/components/nodes/sequentialagents/Condition/Condition.ts, packages/components/nodes/sequentialagents/ConditionAgent/ConditionAgent.ts, packages/components/nodes/sequentialagents/End/End.ts, packages/components/nodes/sequentialagents/LLMNode/LLMNode.ts, packages/components/nodes/sequentialagents/Loop/Loop.ts, packages/components/nodes/sequentialagents/Start/Start.ts, packages/components/nodes/sequentialagents/State/State.ts, packages/components/nodes/sequentialagents/ToolNode/ToolNode.ts, packages/components/src/Interface.ts, packages/server/marketplaces/agentflows/Agentic RAG.json, packages/server/marketplaces/agentflows/Branch Out Merge In.json, packages/server/marketplaces/agentflows/Essay Writing & Grading.json, packages/server/marketplaces/agentflows/Human In Loop RAG.json, packages/server/marketplaces/agentflows/Multi Agents.json, packages/server/marketplaces/agentflows/Patient Concierge.json, packages/server/marketplaces/agentflows/Plan and Execute.json, packages/server/marketplaces/agentflows/Support Routing System.json, packages/ui/src/ui-component/dialog/NodeInfoDialog.jsx, packages/ui/src/utils/genericHelper.js, packages/ui/src/views/canvas/AddNodes.jsx
Update all seg agent nodes to 2.0 for UI UX improvements
=> Feature/Seq Agent Nodes Update

packages/components/nodes/engine/QueryEngine/QueryEngine.ts, packages/components/nodes/engine/SubQuestionQueryEngine/SubQuestionQueryEngine.ts, packages/server/marketplaces/chatflows/Query Engine.json, packages/server/marketplaces/chatflows/SubQuestion Query Engine.json
https://ts.llamaindex.ai/modules/low_level/response_synthesizer The webpage is no longer valid and has been moved to https://ts.llamaindex.ai/modules/response_synthesizer
=> bug-fix:https://ts.llamaindex.ai/modules/low_level/response_synthesizer The webpage has expired.

packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts, packages/server/marketplaces/chatflows/SQL DB Chain.json
fix for the local address in the placeholder
=> bugfix: update placeholder for SQL database connection string

packages/components/nodes/documentloaders/Airtable/Airtable.ts
- Modified: `packages/components/nodes/documentloaders/Airtable/Airtable.ts`
1. **Airtable Node Version Bump**
- Increased version from 3.0 to 3.02
2. **New Input Parameter**
- Added "Filter By Formula" input
```typescript
{
label: 'Filter By Formula',
name: 'filterByFormula',
type: 'string',
placeholder: 'NOT({Id} = "")',
optional: true,
additionalParams: true,
description: 'A formula used to filter records...'
}
```
3. **New Output Option**
- Added "Text" output
```typescript
{
label: 'Text',
name: 'text',
description: 'Concatenated string from pageContent of documents',
baseClasses: ['string', 'json']
}
```
=> Enhance Airtable Document Loader with Filter and Text Output

packages/components/nodes/tools/ChatflowTool/ChatflowTool.ts
=> feat: add support for custom overrideConfig for ChatflowTool

packages/components/nodes/tools/ChainTool/core.ts, packages/components/nodes/tools/ChatflowTool/ChatflowTool.ts, packages/components/src/utils.ts, packages/server/src/utils/buildChatflow.ts
=> Bugfix/Enable Custom Tool Optional Input Schema

packages/components/models.json
=> Feature/Adding the new gemini-1.5-flash-8b model

packages/components/nodes/vectorstores/Postgres/Postgres.ts
=> Update placeholder port to match Postgres default

packages/components/nodes/vectorstores/Milvus/Milvus.ts
Fix the symptoms on this issue #3046
=> fix: Fix [object Object] sent to milvus on search

packages/ui/src/views/canvas/AddNodes.jsx
Fixes https://github.com/FlowiseAI/Flowise/issues/3340
Added support for search on node labels which was earlier not present.
=> fix: added search for node labels

packages/components/credentials/AlibabaApi.credential.ts, packages/components/models.json, packages/components/nodes/chatmodels/ChatAlibabaTongyi/ChatAlibabaTongyi.ts, packages/components/nodes/chatmodels/ChatAlibabaTongyi/alibaba-svgrepo-com.svg, packages/server/src/utils/index.ts
- added ChatAlibabaTongyi node
- added AlibabaApi Credentials
=> feat: Add Alibaba API credential and ChatAlibabaTongyi node

packages/components/nodes/memory/MongoDBMemory/MongoDBMemory.ts, packages/components/nodes/vectorstores/MongoDBAtlas/MongoDBAtlas.ts, packages/components/nodes/vectorstores/MongoDBAtlas/core.ts
- getting rid of singleton design and properly close connection after every interaction
=> Chore/MongoDB Connection

packages/components/credentials/RedisCacheApi.credential.ts
=> Redis default port is 6379

packages/ui/src/views/chatflows/ShareChatbot.jsx
Fixing the bug reported at #3707
=> fix: mapping full file upload configuration

packages/components/nodes/tools/ExaSearch/ExaSearch.ts
Added `financial report` and `linkedin profile` categories.
=> [Feature] Update Exa category filter with new values

packages/components/nodes/retrievers/VoyageAIRetriever/VoyageAIRerankRetriever.ts
as title
see [official docs](https://docs.voyageai.com/docs/reranker)
=> Add `rerank-2` and `rerank-2-lite` for Voyage AI Rerank Retriever

packages/components/models.json
Hey guys, this is my first contribution I noticed that it was not added yet, unless I'm missing anything else, should be it. Hope it helps thanks!
=> Adding DeepSeekR1 Distill to Groq modal

packages/components/nodes/embeddings/JinaAIEmbedding/JinaAIEmbedding.ts
Make dimensions parameter available on JinaEmbeddings
=> Expose dimensions parameter on Jina Embeddings

packages/components/models.json, packages/ui/src/views/docstore/DeleteDocStoreDialog.jsx
=> Update Gemini models as per the Gemini API Documentation.

packages/api-documentation/src/yml/swagger.yml
This pull request includes minor fix to the `packages/api-documentation/src/yml/swagger.yml` file
=> Chore/Fix Swagger YAML formatting

packages/components/nodes/utilities/CustomFunction/CustomFunction.ts, packages/server/src/services/chatflows/index.ts, packages/server/src/utils/buildChatflow.ts, packages/ui/src/ui-component/dialog/ChatflowConfigurationDialog.jsx, packages/ui/src/ui-component/extended/PostProcessing.jsx, packages/ui/src/views/canvas/CanvasHeader.jsx
Added a new feature to process the output from the LLM before it is displayed. In the Chatflow Configuration, new tab (Post Processing) is now available for adding a custom JS function.
=> New Feature: Add post postprocessing of response from LLM using custom JS Function

i18n/README-JA.md, i18n/README-KR.md, i18n/README-TW.md, i18n/README-ZH.md
- Add links to Traditional Chinese (繁體中文) and Simplified Chinese (簡體中文) in the language options of README files
- Create a new Traditional Chinese (繁體中文) README file with detailed instructions for Flowise setup and usage
=> docs: add Traditional and Simplified Chinese README files

packages/components/nodes/tools/MCP/SequentialThinking/SequentialThinkingMCP.ts, packages/components/nodes/tools/MCP/SequentialThinking/sequentialthinking.svg, packages/components/package.json, pnpm-lock.yaml
This PR adds a new MCP tool for sequential thinking that helps break down complex problems into manageable steps.
- Step-by-step thinking process with numbered thoughts
- Support for revising previous thoughts
- Ability to branch into alternative paths
- Dynamic adjustment of total thoughts
- Added SequentialThinkingMCP.ts component
- Created custom SVG icon
- Integrated with the MCP core toolkit
- Tested with the Sequential Thinking MCP server
- Verified tool discovery and action selection
- Confirmed proper integration
[mcp.webm](https://github.com/user-attachments/assets/5fcf7a36-e5a2-43ca-8ab9-e6053c220024)
=> Add Sequential Thinking MCP tool for structured problem-solving

Dockerfile, docker/Dockerfile, docker/docker-compose.yml, packages/server/src/utils/logger.ts
Fixes this issue: https://github.com/FlowiseAI/Flowise/issues/4126
=> Add curl in docker image for native healthchecks

packages/components/models.json
* Add `meta-llama/llama-4-maverick-17b-128e-instruct`
* Add `meta-llama/llama-4-scout-17b-16e-instruct`
=> Add new Llama 4 model options to Groq

README.md, i18n/README-JA.md, i18n/README-KR.md, i18n/README-TW.md, i18n/README-ZH.md
[fix] Document path error & simplified Chinese font is incorrect
=> FIXED Document path error & simplified Chinese font is incorrect

packages/ui/src/ui-component/table/FlowListTable.jsx, packages/ui/src/views/credentials/index.jsx, packages/ui/src/views/variables/index.jsx
Addresses Issue #4250
Shows time in 24 Hr format for Chatflow/Agentflow/Credentials/Variable last modified/update date
=> [FEATURE] Show time with date for last modified date for chatflow/agentflow/credentials/variables

packages/components/models.json
adding cost values to models.json file
=> adding cost values to models.json file

packages/components/models.json
missing costs from models.json for Mistral
=> Adding cost metrics for mistral range of models

packages/server/marketplaces/agentflowsv2/Deep Research V2.json
Output example using `gemini-2.5-flash-preview-04-17` as Agent 2 (the last agent).
[DeepResearch-Agent.pdf](https://github.com/user-attachments/files/20174845/DeepResearch-Agent.pdf)
=> Feature/add Deep Research V2 Template

i18n/README-JA.md, i18n/README-KR.md, i18n/README-TW.md, i18n/README-ZH.md
This pull request fixes broken links to CONTRIBUTING.md and LICENSE.md in i18n README files
Fixes #4465
=> docs: Broken links to CONTRIBUTING.md and LICENSE.md in i18n README files

packages/server/src/enterprise/controllers/workspace-user.controller.ts, packages/server/src/enterprise/middleware/passport/index.ts, packages/server/src/enterprise/services/workspace-user.service.ts, packages/ui/src/api/workspace.js, packages/ui/src/views/workspace/EditWorkspaceUserRoleDialog.jsx, packages/ui/src/views/workspace/WorkspaceUsers.jsx
**Feature: Change role of a workspace user**
*Edit on active users would allow changing of role, without having to unlink and reassign.*
*Change Role Dialog*
Fix for #4388
***Note: the user has to logout and login again for the new role to take effect. The ability to refresh in the same session will come as a separate PR.***
=> New Feature: Ability to change role for a workspace user.

packages/server/src/utils/buildAgentflow.ts
Allow multiple human input nodes logic
=> Bugfix/Multiple Human Input Nodes

packages/server/src/utils/index.ts
Improve the handling of input configurations by merging existing values with overrides instead of complete replacement. This includes support for merging objects and parsing JSON strings when necessary.
=> Bugfix/Allow OverrideConfig For Multiple Nodes In AgentflowV2

packages/server/src/enterprise/services/organization.service.ts, packages/server/src/enterprise/services/stripe.service.ts, packages/server/src/enterprise/webhooks/stripe.ts, packages/ui/src/routes/RequireAuth.jsx
1. Fix list invoice with invalid status in `reactivateOrganizationIfEligible` function.
Before
After
=> Fix stripe-related issues 2

packages/server/src/enterprise/services/stripe.service.ts, packages/ui/src/api/workspace-user.api.js, packages/ui/src/routes/RequireAuth.jsx
Switch member to own workspace after switching to past-due organization.
=> Fix stripe-related issues 3

i18n/CONTRIBUTING-ZH.md
Fix table in CONTRIBUTING-ZH.md
=> Fix table in CONTRIBUTING-ZH.md

packages/components/models.json
Hi, 
This simple PR's adds the newer Gemini models to chatGoogleVertexAI.
=> Added latest vertex models to models.json

packages/ui/src/ui-component/extended/FileUpload.jsx
This simple PR adds the ability to attach yaml to chats
=> Added yaml as a file upload option

packages/components/nodes/outputparsers/StructuredOutputParserAdvanced/StructuredOutputParserAdvanced.ts, packages/components/nodes/tools/CustomTool/CustomTool.ts, packages/components/nodes/vectorstores/Supabase/Supabase.ts, packages/components/nodes/vectorstores/Supabase/filterParser.ts, packages/components/src/secureZodParser.ts
Refactor: Implement SecureZodSchemaParser for safe Zod schema handling and add FilterParser for Supabase filters
* Replaced direct Zod schema evaluation with SecureZodSchemaParser in StructuredOutputParserAdvanced and CustomTool.
* Introduced FilterParser to safely handle Supabase filter strings, preventing arbitrary code execution.
* Added new filterParser.ts file to encapsulate filter parsing logic.
* Updated Supabase vector store to utilize the new FilterParser for RPC filters.
* Created secureZodParser.ts for secure parsing of Zod schemas.
=> Refractor/SecureZodSchemaParser 

packages/server/src/utils/buildAgentflow.ts
- Added support for overriding startState from overrideConfig even when startPersistState is true
=> Bugfix/Override State WhenStartPersistState

packages/components/nodes/agentflow/Iteration/Iteration.ts
Resolves the json parsing issue in Iteration.ts gracefully #5074
=> Fixes problematic json parsing in Iteration.ts

packages/components/nodes/agentflow/Agent/Agent.ts, packages/ui/src/views/agentflowsv2/AgentFlowNode.jsx
feat: add Gemini built-in tools URL Context and Google Search for enhanced functionality
=> Feat/Gemini Built In Tools

packages/ui/src/views/account/index.jsx, packages/ui/src/views/agentflowsv2/Canvas.jsx, packages/ui/src/views/agentflowsv2/MarketplaceCanvas.jsx, packages/ui/src/views/canvas/index.jsx, packages/ui/src/views/marketplaces/MarketplaceCanvas.jsx
Added background toggle functionality across multiple components (AgentflowCanvas, MarketplaceCanvas, Canvas) with new icons for enabling/disabling background.
=> Feature/Grid On Off
