FlowiseAI/Flowise

- packages/components/nodes/documentloaders/Pdf/Pdf.ts
- packages/components/package.json
Previous `pdfjs-dist` package doesn't work, changed to `pdf-parser`
> Bugfix/Use pdf-parser

- packages/server/src/Interface.ts
- packages/server/src/index.ts
- packages/server/src/utils/index.ts
Bug: some nodes were triggered multiple times causing redundant calls
Expected: node should be triggered only once when traversing through the flow
Fix: use BFS to search for starting node ids, store the nodes with same depth levels and retrieve them when `buildLangchain` function is called (another BFS)
> Bugfix/Nodes Get Triggered Multiple Times

- packages/components/nodes/textsplitters/RecursiveCharacterTextSplitter/RecursiveCharacterTextSplitter.ts
> fix typo in description of recursive character text splitter

- packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts
https://github.com/FlowiseAI/Flowise/assets/26460777/23b8bafd-8f42-4bde-9254-f650b44aafbc
> Feature/Add prompt for conversationQA chain

- .github/workflows/main.yml
- .github/workflows/test_docker_build.yml
- Dockerfile
Some changes may accidentally destroy the docker build(see: https://github.com/FlowiseAI/Flowise/issues/217), a CI check is added here to ensure that problems are found in the first place
Additional changes:
> CI: add build docker test

- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
- packages/components/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding.ts
- packages/components/nodes/llms/OpenAI/OpenAI.ts
This pull request is aimed at adding a new configuration option, `basePath`, to the project. This is motivated by the need to support an OpenAI mirror site in China. (such as https://api2d.com/)
The `basePath` will allow users in China to conveniently redirect their requests to a local mirror, thus significantly improving access speed and reliability.
Please consider integrating this change to enhance the user experience for a large number of users in China.
> Add basePath configuration option to support OpenAI mirror 

- packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts
- packages/components/package.json
- packages/components/src/Interface.ts
- packages/components/src/utils.ts
- packages/server/src/Interface.ts
- packages/server/src/entity/ChatMessage.ts
- packages/server/src/index.ts
- packages/ui/src/layout/MainLayout/Header/ProfileSection/index.js
- packages/ui/src/ui-component/dialog/AboutDialog.js
- packages/ui/src/ui-component/dialog/SourceDocDialog.js
- packages/ui/src/views/chatmessage/ChatMessage.js
Add ability to return source documents when using ConversationalRetrievalQAChain:
https://github.com/FlowiseAI/Flowise/assets/26460777/2ba35091-04fa-440b-b3ca-04d7347eb6e4
> Feature/Return SourceDocuments

- packages/components/nodes/textsplitters/LatexTextSplitter/LatexTextSplitter.ts
- packages/components/nodes/textsplitters/LatexTextSplitter/latexTextSplitter.svg
Added the LatexTextSplitter. 
For now I used the Markdown svg logo for it. 
(Created a new PR because the older PRs changes where getting a bit messy to resolve together)
> LatexTextSplitter Integration #226 

- packages/server/src/index.ts
- packages/server/src/utils/index.ts
> add zapier integration

- packages/ui/src/views/chatmessage/ChatMessage.js
Fixed to prevent submission during converting using IME like Japanese
In Safari, `isComposing` is not as expected, so use `keyCode` to determine
https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
If this fix is acceptable,I will also create a PR for FlowiseAI/FlowiseChatEmbed.
> feat: prevent submission during IME composition

- packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
Current bug: 
Streaming prints the output of sql query
Fix:
skip the first LLM streaming, only stream the 2nd part
> Bugfix/SQLDBChain Streaming

- packages/ui/src/views/canvas/AddNodes.js
If you search for a category, then all of the nodes that match that category will show up. This doesn't break existing functionality, as searching for a specific node still reveals that node as expected. I also added a clear button, which will clear and reset the node filter, that way you don't have to manually clear it.
om/FlowiseAI/Flowise/assets/45406132/ad789c0e-caea-48de-a1ac-e03b5edfffcb">
Here are some examples. This is just an update that I personally wanted, I'm happy to make changes or add other QoL features to search that might be nice to have. As the number of nodes grows, search functionality will need to be able to scale.
> Feature/Nodes Search Quality of Life Updates

- Dockerfile
- docker/Dockerfile
- packages/components/nodes/documentloaders/Puppeteer/Puppeteer.ts
A couple of considerations here:
- 1) `--no-sandbox` means that puppeteer and chromium won't execute in a sandbox. This could theoretically have security implications, but since this is in a docker image I doubt it will matter. Maybe something to discuss further.
- 2) I'm not entirely sure the context around `ENV PUPPETEER_SKIP_DOWNLOAD=true` in the Dockerfile, although based on [this pr](https://github.com/FlowiseAI/Flowise/pull/350) it seems that the default install script was causing an error. I'm not seeing this error during build time here, and my thinking is through the Dockerfile there's more control anyway.
> fix: docker should install chromium and puppeteer should be no sandbox

- packages/server/src/utils/index.ts
Results:
**Options**
**Password**
> modify options and password api config

- README.md
- packages/components/nodes/agents/AutoGPT/AutoGPT.ts
- packages/components/nodes/agents/OpenAIFunctionAgent/OpenAIFunctionAgent.ts
- packages/components/nodes/chains/ApiChain/GETApiChain.ts
- packages/components/nodes/chains/ApiChain/OpenAPIChain.ts
- packages/components/nodes/chains/ApiChain/POSTApiChain.ts
- packages/components/nodes/chains/ConversationChain/ConversationChain.ts
- packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts
- packages/components/nodes/chains/LLMChain/LLMChain.ts
- packages/components/nodes/chains/MultiPromptChain/MultiPromptChain.ts
- packages/components/nodes/chains/MultiRetrievalQAChain/MultiRetrievalQAChain.ts
- packages/components/nodes/chains/RetrievalQAChain/RetrievalQAChain.ts
- packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
- packages/components/nodes/chains/VectorDBQAChain/VectorDBQAChain.ts
- packages/components/src/handler.ts
- packages/components/src/utils.ts
- packages/server/.env.example
- packages/server/README.md
- packages/server/src/ChatflowPool.ts
- packages/server/src/ChildProcess.ts
- packages/server/src/commands/start.ts
- packages/server/src/index.ts
- packages/server/src/utils/config.ts
- packages/server/src/utils/index.ts
- packages/server/src/utils/logger.ts
Add `LOG_LEVEL` and more loggers on verbose and debug.
This new changes added logger on every chain/agents, and logger error with stack trace
> Feature/Log Component Level

- packages/server/src/index.ts
Currently the chat message order is coming random because of order of UUID.
Added order by as per the createdDate to ASC to get the chat message in order
> ChatMessage Order Fixed

- README.md
- docker/.env.example
- docker/README.md
- docker/docker-compose.yml
- packages/server/.env.example
- packages/server/README.md
- packages/server/src/index.ts
- packages/server/src/utils/logger.ts
added unwanted log urls to prevent logging node-icon api calls to jsonl file
`server-requests.log.jsonl`
`server.log`
`server-error.log`
`terminal`
> Feature/JSONL Logs Cleanup

- packages/components/nodes/textsplitters/HtmlToMarkdownTextSplitter/HtmlToMarkdownTextSplitter.ts
- packages/components/nodes/textsplitters/HtmlToMarkdownTextSplitter/htmlToMarkdownTextSplitter.svg
- packages/components/package.json
When using webcrawlers as document loaders to embed and store in a Vector Store, much of what is embedded are useless scripts and styles. This creates a semantic mess for the embeddings.
I've introduced a new `HtmlToMarkDownTextSplitter` that inherits from `MarkdownTextSplitter`. This new splitter uses the [`node-html-markdown`](https://www.npmjs.com/package/node-html-markdown) package to convert HTML to Markdown before spliting. Markdown is much more semantically significant for vector embedding.
This approach helps to clean up the embeddings and make them leaner and more meaningful as markdown.
Here's the main code change:
```typescript
splitText(text: string): Promise<string[]> {
return new Promise((resolve) => {
const markdown = NodeHtmlMarkdown.translate(text) …
```
> New Html To Markdown TextSplitter

- packages/ui/src/views/chatflows/APICodeDialog.js
this is copy from [discord](https://discord.com/channels/1087698854775881778/1096265567058534461/1130069743760588883)
after I deploy flowise on render.com and make some LLM chain, we can not call the LLM via curl and javascript, but python can connect.
after some workaround, I found we have to explicitly specify the encoding of data in JSON, for example adding -H "Content-Type: application/json"in curl command.
python do this specification and thus no error happened.
this is jacascript version
> Refactor API request to include Content-Type header

- packages/ui/src/views/chatflows/APICodeDialog.js
this is copy from [discord](https://discord.com/channels/1087698854775881778/1096265567058534461/1130069743760588883)
after I deploy flowise on render.com and make some LLM chain, we can not call the LLM via curl and javascript, but python can connect.
after some workaround, I found we have to explicitly specify the encoding of data in JSON, for example adding -H "Content-Type: application/json"in curl command.
python do this specification and thus no error happened.
this is curl version
> add -H "Content-Type: application/json" in curl command

- packages/components/nodes/chains/LLMChain/LLMChain.ts
When using few shot prompt, promptValues is undefined: 
This is a minor fix when promptValues is undefined
> Bugfix/LLMChain PromptValues Undefined

- packages/components/nodes/agents/CSVAgent/CSVAgent.ts
Result:
additional `systemMessagePrompt ` added by users
if no additional `systemMessagePrompt` added by users
> add additional systemMessagePrompt into CSV Agent

- packages/components/nodes/documentloaders/Folder/Folder.ts
For now added additional input parameters to allow addition of more file loaders. Not sure if this will work well. I couldn't get the main brand to build successfully locally so I couldn't run any of the tests. I highly suggest testing this locally before approving the pull request. Original issue: Issue #731.
> Issue #731: Add additional optional input parameter for adding additional file loaders

- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
Had the need to pass Helicone's API key but there was no way to pass the BaseOptions needed on the documentation. 
Used a very similar code to pupeteer's node metadata input. Just added a try..catch, in case something is wrong with the JSON, so the user can identify where it is coming from.
_BaseOptions on ChatOpenAI node_
_Example call to Helicone_
_Custom properties working as well, so any use you may have for BaseOptions now are possible_
> Added BaseOptions to ChatOpenAI

- packages/components/nodes/vectorstores/Faiss_Existing/Faiss_Existing.ts
- packages/components/nodes/vectorstores/Faiss_Upsert/Faiss_Upsert.ts
- packages/server/src/index.ts
- packages/server/src/utils/index.ts
> Feature/FaissVS Streaming

- packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
- packages/server/marketplaces/chatflows/SQL DB Chain.json
> Feature/Add custom prompt to SQLDbChain

- packages/components/nodes/documentloaders/Github/Github.ts
- packages/server/marketplaces/chatflows/Flowise Docs QnA.json
> Feature/GithubLoader AdditionalParams

- packages/server/marketplaces/tools/Get Current DateTime.json
```
// Define the desired time zone
const timeZone = 'Australia/Sydney';
// Define an options object to format the date and time
const options = {
timeZone: timeZone,   // Set the time zone
year: 'numeric',       // Display the year as a number
month: 'long',         // Display the full month name
day: 'numeric',        // Display the day of the month as a number
weekday: 'long',      // Display the full weekday name
hour: '2-digit',       // Display the hour in 2-digit format (00-23)
minute: '2-digit',     // Display the minute in 2-digit format (00-59)
second: '2-digit',     // Display the second in 2-digit format (00-59)
hour12: true           // Use 12-hour time format (AM/PM)
};
// Create a new Date object representing the current date and time
const today = new Date();
// Format the …
```
> feat: dateTime marketplace tool

- packages/components/nodes/chatmodels/ChatGoogleVertexAI/ChatGoogleVertexAI.ts
- packages/components/nodes/llms/GoogleVertexAI/GoogleVertexAI.ts
Adaptation of [32k model of Vertex AI Embedding](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models#32k_models), which is published Google Could Next on last week! 🎉
> add 32k model

- packages/components/credentials/GoogleMakerSuite.credential.ts
- packages/components/nodes/llms/GooglePaLM/GooglePaLM.ts
- packages/components/nodes/llms/GooglePaLM/Google_PaLM_Logo.svg
- packages/components/package.json
This is a first draft of the the LLM component for the PaLM API (ref: #862)
Could you have a look at the overall style? 
Once this part is satisfactory, I can do PaLM-Chat and PaLM-embeddings to match...
For the update to package.json : I wasn't sure how to make sure this installed when building overall, since it's required by langchain, but didn't seem to have installed itself.
I noticed that the 'json' field in the optional parameters don't seem to be properly editable - either on this component, or on the existing OpenAI one - so maybe that needs an additional fix.
> PaLM API LLM component

- CONTRIBUTING-ZH.md
- CONTRIBUTING.md
- docker/.env.example
- docker/docker-compose.yml
- packages/components/src/utils.ts
- packages/server/.env.example
- packages/server/README-ZH.md
- packages/server/src/commands/start.ts
- packages/server/src/utils/index.ts
- Ability to use `FLOWISE_SECRETKEY_OVERWRITE` to replace the key set in `SECRETKEY_PATH`. 
- Issues related:
- https://github.com/FlowiseAI/Flowise/issues/915
- https://github.com/FlowiseAI/Flowise/issues/643
- https://github.com/FlowiseAI/Flowise/issues/896
- https://twitter.com/_alissonryan/status/1702819282848031048
> Feature/Add FLOWISE_SECRETKEY_OVERWRITE

- packages/components/nodes/documentloaders/Cheerio/Cheerio.ts
Added selector parameter to Cheerio web loader
As described here: https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/web_cheerio
Improves the quality of the scraped content A LOT
> Added CSS selector to Cheerio

- packages/ui/src/views/marketplaces/index.js
> Duplicate icon when market is empty

- packages/components/nodes/retrievers/SimilarityThresholdRetriever/SimilarityThresholdRetriever.ts
- packages/components/nodes/retrievers/SimilarityThresholdRetriever/similaritythreshold.svg
> Feature/Similarity Threshold Retriever

- packages/components/nodes/agents/ConversationalAgent/ConversationalAgent.ts
- packages/components/nodes/agents/ConversationalRetrievalAgent/ConversationalRetrievalAgent.ts
- packages/components/nodes/agents/OpenAIFunctionAgent/OpenAIFunctionAgent.ts
- packages/components/nodes/chains/ConversationChain/ConversationChain.ts
- packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts
Bug: when using RedisBackedChatMemory, the `chatHistory` is being override with `InMemory`, causing it not to work.
Fix: place a check to only replacing history if `InMemory` is being used.
`InMemory` nodes are `BufferMemory`, `BufferWindowMemory`, `ConversationSummaryMemory`
> Bugfix/Redis Backed Memory fix

- packages/components/nodes/documentloaders/PlainText/PlainText.ts
- packages/components/nodes/documentloaders/Text/Text.ts
Added possibility to select "Text output" instead of "Document" for components "Text File" and "Plain Text". It allows to use the output directly as a value of a variable in prompt.
> Text output for Text File and Plain Text components

- packages/components/src/handler.ts
- packages/ui/src/ui-component/dialog/AnalyseFlowDialog.js
The optional inputs `flushAt`, `flushInterval` and `requestTimeout` only need to be changed in edge cases. I suggest to remove them from Flowise to simplify getting started with Langfuse.
> Remove unnecessary Langfuse inputs

- packages/components/nodes/chains/ConversationChain/ConversationChain.ts
- packages/components/nodes/prompts/ChatPromptTemplate/ChatPromptTemplate.ts
@deprecated — Renamed to .fromMessages
> fix: ChatPromptTemplate function name

- packages/server/bin/.gitattributes
As an alternative to the failed PR #1054 from me, I've created a new fix that simply adds `.gitattributes` to the folder where the `dev` and `run` scripts exist and no other changes.
This causes git to put the proper line endings when it touches the file. As a note, any existing clone will continue to fail to build Docker on Windows, but if the file is touched or the repo is re-cloned, it will work.
I tested this fix on both Windows and Linux Ubuntu 22.04.6 LTS Docker builds. In both cases it built, deployed and ran properly. So I am hoping this will fix #911 without further issues.
> Fix for #911, CRLF line endings, new fix.

- packages/components/nodes/vectorstores/Postgres_Existing/Postgres_Exisiting.ts
- packages/components/nodes/vectorstores/Postgres_Upsert/Postgres_Upsert.ts
> Feature/Postgres VS additional config

- packages/components/nodes/prompts/ChatPromptTemplate/ChatPromptTemplate.ts
- packages/components/nodes/prompts/FewShotPromptTemplate/FewShotPromptTemplate.ts
- packages/components/nodes/prompts/PromptTemplate/PromptTemplate.ts
- packages/components/nodes/textsplitters/RecursiveCharacterTextSplitter/RecursiveCharacterTextSplitter.ts
Currently when using `overrideConfig` for json object, it causes error:
```
"overrideConfig": {
"promptValues": {
"input_language": "English",
"output_language": "Italian"
}
}
```
Fix: only parse it when it is a string
> Bugfix/Add JSON parse fix

- packages/components/nodes/agents/CSVAgent/CSVAgent.ts
- packages/components/nodes/memory/BufferWindowMemory/BufferWindowMemory.ts
- packages/components/nodes/memory/ZepMemory/ZepMemory.ts
- packages/components/nodes/prompts/FewShotPromptTemplate/FewShotPromptTemplate.ts
- packages/components/nodes/textsplitters/CharacterTextSplitter/CharacterTextSplitter.ts
- packages/components/nodes/textsplitters/RecursiveCharacterTextSplitter/RecursiveCharacterTextSplitter.ts
- packages/components/src/utils.ts
- packages/server/marketplaces/chatflows/Antonym.json
Fixed the spellings across multiple files.
> Spelling Corrections.

- packages/components/nodes/vectorstores/Milvus/Milvus_Upsert.ts
Error: "Property 'INDEX_NOT_EXIST' does not exist on type 'typeof ErrorCode'. Did you mean 'IndexNotExist'?ts(2551)
error.d.ts(39, 5): 'IndexNotExist' is declared here."
in "packages/components/nodes/vectorstores/Milvus/Milvus_Upsert.ts".
Fixed: Replaced INDEX_NOT_EXIST with IndexNotExist
issue described here: #1135
> Build error fixed (TS)

- packages/components/nodes/vectorstores/InMemory/InMemoryVectorStore.ts
undefined document pagecontent is causing reading issue with replace function.
fix for:
#1106  #1123
> [Bug] Fix Cannot read properties of undefined (reading 'replace')

- packages/components/nodes/chains/ConversationChain/ConversationChain.ts
- packages/components/nodes/vectorstores/Chroma/Chroma_Upsert.ts
- packages/components/nodes/vectorstores/Elasticsearch/Elasticsearch_Upsert.ts
- packages/components/nodes/vectorstores/Faiss_Upsert/Faiss_Upsert.ts
- packages/components/nodes/vectorstores/InMemory/InMemoryVectorStore.ts
- packages/components/nodes/vectorstores/Milvus/Milvus_Upsert.ts
- packages/components/nodes/vectorstores/OpenSearch_Upsert/OpenSearch_Upsert.ts
- packages/components/nodes/vectorstores/Pinecone/Pinecone_Upsert.ts
- packages/components/nodes/vectorstores/Postgres_Upsert/Postgres_Upsert.ts
- packages/components/nodes/vectorstores/Qdrant_Upsert/Qdrant_Upsert.ts
- packages/components/nodes/vectorstores/Redis/Redis_Upsert.ts
- packages/components/nodes/vectorstores/Singlestore_Upsert/Singlestore_Upsert.ts
- packages/components/nodes/vectorstores/Vectara/Vectara_Upsert.ts
- packages/components/nodes/vectorstores/Weaviate_Upsert/Weaviate_Upsert.ts
- packages/components/nodes/vectorstores/Zep/Zep_Upsert.ts
add check before adding new document
> Bugfix/Cannot read properties of undefined (replace)

- packages/components/src/Interface.ts
- packages/ui/src/views/canvas/CanvasNode.js
This feature adds the ability for node params to mark themselves as `hidden` from the UI.
This is required for nodes which don't have static API credentials, but rather have session context tokens or otherwise that are dependent and change when the chatbot is embedded, and should not be set in the UI.
These params can still be targeted and passed a value through `chatflowConfig` options. In addition, the `i` info button continues to show these parameters inside of `NodeInfoDialog` so that developers know they exist.
> Adding ability to hide node param from UI

- packages/components/credentials/ElectricsearchUserPassword.credential.ts
- packages/components/nodes/vectorstores/Elasticsearch/ElasticSearchBase.ts
In the credential nodeId can be inserted a custom server URL and the basic auth will be used.
> Enable inserting custom URL  using basic auth

- packages/components/credentials/MongoDBUrlApi.credential.ts
The placeholder url raises a false positive on GitGuardian (leakage of MongoDB secrets).
> GitGuardian - Fix for MongoDB False Positive Alert

- packages/server/src/index.ts
- packages/server/src/utils/apiKey.ts
- packages/server/src/utils/index.ts
Hello!
I'm just starting to contribute to flowise. I noticed some opportunities to refactor the code for better maintainability.
This PR moves utilities relating to api keys from `utils/index.ts` to `utils/apiKey.ts`. I think this better fits the pattern of the folder.
Let me know how this goes and I can contribute further similar improvements.
> Refactor: Move api key utilities to separate file

- packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts
- packages/components/nodes/memory/DynamoDb/DynamoDb.ts
- packages/components/nodes/memory/MongoDBMemory/MongoDBMemory.ts
- packages/components/nodes/memory/MotorheadMemory/MotorheadMemory.ts
- packages/components/nodes/memory/RedisBackedChatMemory/RedisBackedChatMemory.ts
- packages/components/nodes/memory/UpstashRedisBackedChatMemory/UpstashRedisBackedChatMemory.ts
- packages/components/nodes/memory/ZepMemory/ZepMemory.ts
- packages/components/nodes/tools/ChainTool/core.ts
- packages/components/src/Interface.ts
- packages/components/src/utils.ts
- packages/server/src/index.ts
- packages/server/src/utils/index.ts
Bug: When specifying prompt variable using chatHistory:
It is empty when:
- used together with Memory nodes with SessionId
- called via API
Reason being there is no `incomingInput.history` passed from the API body request.
Fix: retrieve chat history automatically when detected `incomingInput.history` is empty.
> Bugfix/Empty ChatHistory

- packages/ui/src/views/canvas/index.js
This commit fixes #1323 that I found.
Previously after deleting it was calling `navigate('-1')`, but if it's duplicate it's in a new window with no history.
Here I changed it to `navigate('/')` which will have almost identical behaviour (in almost all cases they come from chatflows) and fixes the defect.
> Fix for issue#1323 - delete duplicate chatflow

- packages/ui/src/ui-component/button/FlowListMenu.js
- packages/ui/src/views/chatflows/index.js
This fixes #1324 by lifting `ConfirmDialog` up so there isn't N of them created, 1 for each list menu item.
> Fixing #1324 by lifting ConfirmDialog up.

- packages/components/nodes/memory/ZepMemory/ZepMemory.ts
- packages/components/package.json
- packages/server/marketplaces/chatflows/Long Term Memory.json
Update Zep to handle summary automatically:
> Feature/Update Zep version

- packages/ui/src/ui-component/table/FlowListTable.js
- packages/ui/src/views/chatflows/index.js
remove console warning in below three.
> bugfix_console_warning

- packages/server/src/ChatflowPool.ts
- packages/server/src/Interface.ts
- packages/server/src/index.ts
Steps to replicate:
1.) Construct a RAG flow and upsert the document through UI:
2.) Hit `/api/v1/vector/upsert` API to upload another document:
3.) Back to UI or use `/prediction` API to ask something about the 2nd document.
Expected: answer can be succesfully retrieved from vector store
Actual: AI answer dont know
Bug: `overrideConfig` is not being saved to `ChatflowPool`, causing the flow to be reused.
Fix: save the `overrideConfig`, causing flow to be re-executed from the start, hence calling the `init` of the vector store, loading the new stuff in
> Bugfix/Upsert Vector API

- packages/server/src/index.ts
When `&` presents in the query: for example - `/api/v1/credentials?credentialName=redisCacheApi&credentialName=redisCacheUrlApi`
The sanitized url becomes - `/api/v1/credentials?credentialName=redisCacheApi&amp;credentialName=redisCacheUrlApi`
> Bugfix/Sanitized &amp

- packages/components/nodes/vectorstores/Elasticsearch/Elasticsearch.ts
In the new Elastic node, there is the same connection error that was solved in the deprecated nodes whenever connecting to a custom server URL. 
The bug was previously solved in #1262
> [BUGFIX/REGRESSION] Fix wrong elastic client setup when use custom URL

- packages/components/nodes/memory/RedisBackedChatMemory/RedisBackedChatMemory.ts
See: https://github.com/FlowiseAI/Flowise/issues/615
This is resolve the "token exceeded error" for redis backed memory.
> Add windowSize input to avoid "token exceeded error"

- packages/components/nodes/vectorstores/Redis/Redis.ts
- packages/server/marketplaces/chatflows/Multiple VectorDB.json
- packages/server/src/index.ts
- packages/server/src/utils/index.ts
Bug:
1.) Consider a flow with multiple vector nodes
2.) When click Upsert pop up, you will see multiple vector upserts:
3.) Suppose you click the first Upsert (Redis), you are expecting the nodes to run through only those nodes presented on UI (Plain Text -> OpenAI Embedding -> Redis). However currently it run through every nodes, including the nodes below
Fix: Find only relevant connected nodes from the vector node
> Bugfix/Multiple Vector Upsert

- packages/components/nodes/documentloaders/Notion/NotionDB.ts
Bugfix:: NotionDB Loader failed to insert documents into the vector store.
> Bugfix: Upsert successful, but failed to insert documents

- README.md
Integration with RepoCloud Deploy Template to the Flowise GitHub page, enabling one-click deployment. This addition simplifies the process for users to quickly deploy and scale Flowise using RepoCloud's efficient cloud hosting services.
> Added deploy template for RepoCloud.io

- packages/components/nodes/vectorstores/Milvus/Milvus.ts
langchain python use `text` 
https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py#L119
while langchian js use `langchain_text` 
https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/milvus.ts#L61
so it is necessary to add milvusTextField configuration for Milvus.
> Add milvusTextField configuration for Milvus

- docker/README.md
The current link requires authentication to view, the new link is the public repo page for the image.
> Correct DockerHub link in docs from private to public repo page

- packages/components/package.json
- packages/components/src/handler.ts
- Add sessionId tracking on Langfuse.
- User can also add additional configs like:
```
{
"question": "hi there",
"overrideConfig": {
"analytics": {
"langFuse": {
"userId": "user1"
}
}
}
}
```
> Feature/SessionId Tracking

- package.json
The cause of #1535 is the older version of turbo, as per https://github.com/vercel/turbo/issues/5650.
This PR updates turbo to the latest compatible version to fix a bug with GitHub actions not able to build arm64 docker images.
Fixes #1535.
> Fix for #1535

- packages/components/nodes/utilities/CustomFunction/CustomFunction.ts
When the input contains FLOWISE_DOUBLE_QUOTE, it will not be parsed using JSON.parse.
> Fix CustomFunction receiving excaped inputs

- packages/components/package.json
- Locks the `@upstash/redis` version in `components/package.json`. This was causing issues with deployments and when adding credentials.
> FIX: Upstash redis error causing deployment and adding credentials error

- packages/components/nodes/llms/Azure OpenAI/AzureOpenAI.ts
Hey @HenryHengZJ , I've updated the AzureOpenAI LLM node to support gpt-4 and gpt-4-32k models, since those were missing from the dropdown selectors.  Let me know if you have any questions. Thanks!
> Added support for gpt-4 and gpt-4-32k models

- packages/components/nodes/utilities/CustomFunction/CustomFunction.ts
- packages/server/src/index.ts
closes #1590 
With this PR, we can set CustomFunction as an Ending Node.
> Allows CustomFunction to be set as an Ending Node.

- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
[OpenAI Blog notice](https://openai.com/blog/new-embedding-models-and-api-updates)
- added the new gpt-4-0125-preview
- added the latest model alias: gpt-4-turbo-preview
> Update ChatOpenAI.ts to include new openai's Chat models

- packages/server/src/DataSource.ts
fixing issue related to bug https://github.com/FlowiseAI/Flowise/issues/1582
While using DB of 'mysql' (and I believe others which are not 'sqlite') there's an error saying:
**ENOENT: no such file or directory, open '/root/.flowise/settings.json** 
It happens since the root/.flowise directory wasn't exist before trying to write the 'settings.json' file over
https://github.com/FlowiseAI/Flowise/blob/5d25c35a1ac4250bb79b21bc22243576a18b2e36/packages/server/src/utils/telemetry.ts#L31
@HenryHengZJ please review
Thanks
> fix bug settings.json not found on upsert

- CONTRIBUTING.md
- docker/.env.example
- docker/docker-compose.yml
- packages/server/.env.example
- packages/server/src/commands/start.ts
- packages/server/src/index.ts
- packages/server/src/utils/XSS.ts
This PR implements both [Cross Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) frame ancestors headers.
Both are very important from a security standpoint, with CSP specifically stopping XSS attacks (iframe embedding).
These new options use two new _optional_ env variables:
```
```
By default both are not set and backwards compatible. If they are not set, we do not emit CSP headers (as before), and CORS sends the origin domain (also as before).
Here's an example that allows CORS requests and embedding from a specific domain:
```
CORS_ORIGINS="https://www.testme.com"
EMBEDDING_ORIGINS="https://www.testme.com"
``` …
> Implementing CORS and CSP headers from config

- packages/components/nodes/embeddings/AzureOpenAIEmbedding/AzureOpenAIEmbedding.ts
This fixes https://github.com/FlowiseAI/Flowise/issues/1626
> Bugfix/AzureOpenAIEmbedding - Updated Default Batch Size from 1 to 100

- packages/components/nodes/agents/OpenAIFunctionAgent/OpenAIFunctionAgent.ts
- packages/components/nodes/outputparsers/CustomListOutputParser/CustomListOutputParser.ts
- packages/components/nodes/tools/RetrieverTool/RetrieverTool.ts
- packages/components/src/agents.ts
- packages/server/marketplaces/chatflows/Conversational Retrieval Agent.json
- packages/server/src/index.ts
> Feature/Return Source Documens to retriever tool

- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
Include newly-released gpt-3.5-turbo-0125 to available models in Chat/OpenAI node
> Add newly-released gpt-3.5-turbo-0125 to ChatOpenAI

- packages/components/nodes/documentloaders/Folder/Folder.ts
I noticed that Kotlin files were not loaded via the folder loader.
This PR now adds this file type.
> add kotlin files to folder-loader

- packages/server/src/index.ts
I used OpenAI's Assistant in ChatFlow and differentiated users based on their chatId.
Then, when I wanted to retrieve the user's chat message history based on the unique `chatId`, I had to first call `/chatmessage/${chatflowid}` to get all the historical chat messages. Then, I filtered the chat message based on `chatId` and obtained the `sessionId`. After that, I called `/chatmessage/${chatflowid}?chatId=${chatId}&sessionId=${sessionId}` to retrieve the user's chat message.
> 💡 Flowise internal `sessionId` is the `threadId` returned by Assistant and cannot be overwritten.
> ⚠️ Calling `/chatmessage/${chatflowid}` will retrieve all chat messages, which is not ideal.
The reason for needing to retrieve the chat history of a single user is because when querying the database, if only the …
> [Bufix] Modify the default value of sessionId when fetching history chat messages.

- packages/components/nodes/memory/DynamoDb/DynamoDb.ts
Fixes #1624
Please note comment in class BufferMemoryExtended for further discussion, if necessary
> DynamoDB Chat Memory fix

- packages/components/nodes/vectorstores/Postgres/Postgres.ts
Hey @HenryHengZJ, as a follow up to this comment:
https://github.com/FlowiseAI/Flowise/pull/1107#issuecomment-1925593846
The core bug currently is:
- If you configure a Postgres DB to *ONLY* accept remote TLS/SSL connections
- You specify similar `additionalConfig` settings (see below)
- Then the node *will* successfully upsert documents into Postgres via TLS/SSL
- BUT, when you attempt to use the node's `similaritySearchVectorWithScore` function for comparisons, those connections will *fail* because the node attempts to connect to the Postgres DB in the clear (not using TLS/SSL) -- even though the settings were specified in `additionalConfig`
Here's a PR that covers the bugfix for getting the Postgres vectorstore node to actually talk to the DB via TLS/SSL all the time.  Previously, if …
> Fixing Postgres so that similaritySearchVectorWithScore actually connects via TLS/SSL when specified

- packages/components/nodes/documentloaders/Cheerio/Cheerio.ts
- packages/components/nodes/documentloaders/Playwright/Playwright.ts
- packages/components/nodes/documentloaders/Puppeteer/Puppeteer.ts
- packages/server/src/index.ts
- packages/ui/src/api/scraper.js
- packages/ui/src/ui-component/dialog/ManageScrapedLinksDialog.js
- packages/ui/src/views/canvas/NodeInputHandler.js
- Fixes `relativeLinksMethod` and `limit` values set in Additional Parameters in `Cheerio`, `Playwright`, and `Puppeteer` nodes.
> Fix: relative links method and limit not applying to manage links

- packages/server/src/index.ts
This will be useful when the exact message is required by another system. For example, you want a microservice that performs additional work (search query caching, convert to voice, create a video, etc) and it need to be associated to that exact message in some sort of backend (likely graphql) that merges the messages with the augmented data.
> Allows query chatmessage API endpoint by messageId

- packages/server/src/index.ts
previous logic for where clause of memoryType checked for existence of chatId and would query for memoryType is null This where clause logic results in an empty result for any request to the endpoint that filters by chatId
Getting messages without any filters
filtering by known chatId value using existing where clause
filtering by known chatId value using new where clause logic for memoryType
> fixes bug where querying by chatId results in no records

- package.json
The latest version of a dependency (`@qdrant/openapi-typescript-fetch`) in the `@qdrant/js-client-rest` package causes an error when starting the Flowise server. This also caused an issue with adding credentials. Pinning the previous version of the dependency in the root `package.json` fixes the issue.
Before:
After:
> FIX: ES module import issue in Qdrant package

- packages/ui/src/views/chatflows/index.js
- packages/ui/src/views/marketplaces/index.js
Chatflow Dashboard and Market Place Dashboard - When the view toggle is clicked twice, the state is lost (toggle on/off).
> Bugfix: View Toggle loses state when button is clicked twice.

- packages/server/src/NodesPool.ts
- packages/server/src/index.ts
Currently, the following file results in an error: Flowise/packages/components/dist/nodes/documentloaders/Subtitles/Subtitles.js:3:15 The result is that initializeNodes fails completely, and all other code in initDatabase fails to load
> handles scenario where NodesPool require call fails

- packages/server/src/utils/index.ts
with this PR, we can set partial value. no need to set full config.
- case 1:
```sh
curl http://127.0.0.1:8711/api/v1/prediction/be46c4d4-52cf-4d1b-9a76-c195643dfa0b \
-X POST \
-d '{"question": "Hey, how are you?", "overrideConfig": {"config": {"ver":123} }}' \
-H "Content-Type: application/json"
```
- case 2:
```sh
curl http://127.0.0.1:8711/api/v1/prediction/be46c4d4-52cf-4d1b-9a76-c195643dfa0b \
-X POST \
-d '{"question": "Hey, how are you?", "overrideConfig": {"config": {"url": "https://github.com"} }}' \
-H "Content-Type: application/json"
```
> Feature: OverrideConfig allows partial override

- packages/server/src/index.ts
Testing code is more cumbersome when CustomFunction requires input variables.
```js
const question = $question ?? 'my default question'
```
> Allow default variable values ​​when testing CustomFunction

- packages/server/src/index.ts
- packages/ui/src/ui-component/dialog/ManageScrapedLinksDialog.js
- Prevents server from crashing if link is empty or invalid. Instead returns an error message.
- Disable "Fetch Links" button when input is empty.
- Adds a clear all button to quickly remove all the fetched links.
> Fix: Error Handling in Web Scraper

- packages/components/nodes/utilities/CustomFunction/CustomFunction.ts
- packages/components/nodes/utilities/IfElseFunction/IfElseFunction.ts
This PR relates to https://github.com/FlowiseAI/Flowise/pull/1539 . If it is json after unescaping, it will be parsed into a json object.
> Fix CustomFunction deserializing escaped JSON strings

- packages/server/src/utils/index.ts
This PR supports `{{<variableNodeId>.data.instance.pathtokey}}`.
---
This is useful for PromptTemplate to get the value of one of its fields from the previous node json value output.
> Feature: Add support for accessing NodeData via json path

- packages/server/src/index.ts
Fixed the issue of inconsistent date creation, if the running server and the database are in different regions, the generated date will be inconsistent, and the generated date will be inconsistent
> Fixed a bug about conversation dates

- packages/components/nodes/utilities/IfElseFunction/IfElseFunction.ts
Modified ifelse function node logic to follow the behaviour from customfunction node
As discussed this PR addresses the fix for #1887
> fix(utilities): Handle escape characters in ifelse-function node's return value, resolves #1887

- packages/server/src/utils/index.ts
> Fix duplicated calculation of nodes and dependent nodes are not initialized

- packages/components/nodes/utilities/SetVariable/SetVariable.ts
Bug: Set Variable input always has an array like `['value']`, this causes error when Get Variable is called to retrieve the variable
> Bugfix/Set Variable

- package.json
- pnpm-lock.yaml
Fixes an error thrown by the Faiss node when using pnpm to install packages.
> Fix: Faiss vector store throws error when using pnpm

- packages/ui/src/ui-component/cards/StarterPromptsCard.css
When starter prompts are long or when we have more than 3, the prompts exceed the chat window. It's only scrollable with a trackpad and doesn't show a scrollbar. Now prompts will wrap, which is the behavior in embed.
> Fix: starter prompts exceeds chat window and cannot be scrolled

- .github/workflows/main.yml
The action follows [actions/cache](https://github.com/actions/cache/blob/main/examples.md#node---npm) guidelines, and caches global cache on the machine instead of node_modules, so cache can be reused between different Node.js versions.
Caching pnpm (v6.10+) dependencies
NOTES:
- pnpm caching support requires pnpm version >= 6.10.0
- By default --frozen-lockfile option is passed starting from pnpm 6.10.x. It will be automatically added if we run it on [CI](https://pnpm.io/cli/install#--frozen-lockfile). If the pnpm-lock.yaml file changes then we have to pass --frozen-lockfile option.
> Enable github workflow pnpm caching

- .github/workflows/autoSyncMergedPullRequest.yml
- .github/workflows/autoSyncSingleCommit.yml
Allow multi-line commit message to be used in autosync workflows using the [toJSON context function](https://docs.github.com/en/actions/learn-github-actions/expressions#tojson)
> Send valid JSON to autosync workflows for multi-line commit messages

- packages/ui/src/views/chatflows/APICodeDialog.jsx
The current url takes you to 404. Updated the href.
> fix: update streaming how-to url

- packages/components/nodes/tools/AIPlugin/AIPlugin.ts
**I have noticed that we don't have to use the AIPlugin in nodes under the tools section because the ChatGPT Plugin is winding down on March 19. This means the endpoints will no longer function, which could lead to bugs. Users who are already using the AIPlugin tool should be notified via the Badge (DEPRECATING) so they are aware that they should not use this tool in production.**
[https://help.openai.com/en/articles/8988022-winding-down-the-chatgpt-plugins-beta](https://help.openai.com/en/articles/8988022-winding-down-the-chatgpt-plugins-beta
)
> bugfix: depreciating chatgpt plugin

- packages/components/nodes/documentloaders/Cheerio/Cheerio.ts
- packages/components/nodes/documentloaders/Playwright/Playwright.ts
- packages/components/nodes/documentloaders/Puppeteer/Puppeteer.ts
Bug: when `limit` set to 0, `selectedLinks` sliced to become empty
Expected: if `selectedLinks` is not empty AND `limit` is 0, `pages` == `selectedLinks`
> Bugfix/Web Scraper Limit

- packages/server/src/database/migrations/mysql/1709814301358-AddUpsertHistoryEntity.ts
while running latest deployment I'm getting the following syntax error for mysql db:
Migration "AddUpsertHistoryEntity1709814301358" failed, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'KEY `IDX_a0b59fd66f6e48d2b198123cb6` (`chatflowid`)) ENGINE=InnoD' at line 8
There was missing comma which fixed that,
@HenryHengZJ please review
> fix missing comma upon sql migration query

- packages/ui/src/views/vectorstore/UpsertHistoryDialog.jsx
Steps to reproduce:
1) Create a new chatflow with InMemory VectorStore and do an upsert.
2) Click on Upsert History Dialog from settings
3) Expand Accordion - Details 
4) Expand the InMemory Accordion
> Unable to view upsert history dialog, when InMemoryVector Store is used

- .github/workflows/main.yml
- Dockerfile
- package.json
[Related comment](https://github.com/FlowiseAI/Flowise/commit/d07bd96c7b30a7d0d0b69a70becffae3f6039d1f#commitcomment-141075889)
> Fix pnpm version for CI

- packages/server/src/services/chatflows/index.ts
- packages/server/src/utils/buildChatflow.ts
- packages/server/src/utils/index.ts
If there are multiple end nodes, only one needs to pass verification, and the others are automatically ignored. 
This allows us to temporarily disconnect a node without deleting it.
> Optimize `getEndingNodes`

- packages/components/nodes/documentloaders/Folder/Folder.ts
Folder with Files 
By default, a separate document is created for each page in the PDF file. 
This setting can be modified to create one document per PDF file
> Feature: Add pdfUsage parameter setting support to folderFiles

- packages/ui/src/views/canvas/index.jsx
This is a simple typo fix which changes `error` in the various responses to the proper variable to avoid the undefined error in the dev console.
> Closes #2228

- packages/components/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding.ts
- packages/components/nodes/embeddings/OpenAIEmbeddingCustom/OpenAIEmbeddingCustom.ts
This pull request introduces enhancements to the OpenAI embedding components within the Flowise repository. Specifically, new functionality has been added to the `OpenAIEmbedding` and `OpenAIEmbeddingCustom` classes allowing users to specify the dimension size of the embeddings returned by the models. This feature leverages the new capabilities of the `text-embedding-3` class models from the langchain package.
https://js.langchain.com/docs/integrations/text_embedding/openai#specifying-dimensions
1. **Addition of 'Dimensions' Parameter:**
- Both `OpenAIEmbedding` and `OpenAIEmbeddingCustom` classes now include a new input parameter labeled 'Dimensions' that accepts a number specifying the desired size of the embeddings. This parameter is optional and defaults to the maximum dimensions …
> Add Custom Dimensionality Support for OpenAI Embedding Components

- packages/components/models.json
- packages/components/nodes/chatmodels/Groq/Groq.ts
Added support for `models.json` with GroqChat and included the current models in the list.
> models.json support for Groq

- packages/components/nodes/documentloaders/Csv/Csv.ts
This fixes the typo where the CSV document loader doesn't work if a text splitter isn't specified.
> Fixes 2343 CSV error with no text splitter

- packages/server/src/index.ts
The initDatabase function in App class was not awaiting for its completion. Added a await keyword and refactored the catch in try catch block.
> fix initDatabase function by proper use of await in try catch

- packages/components/models.json
- packages/ui/src/views/assistants/AssistantDialog.jsx
OpenAI announced GPT-4o, their new flagship model that can reason across audio, vision, and text in real-time.
**Reference:** [Hello GPT-4o](https://openai.com/index/hello-gpt-4o/)
> Add new openai model (GPT-4o ) in the assistant and models.json

- packages/components/models.json
**Description:**
In the "models" array:
- Added a "description" field for each bedrock model, providing a brief overview of the model's capabilities.
- Updated the "name" field for some models by appending a version number (e.g., ":0", ":1", ":2") to the model name.
- Added new models:
- "anthropic.claude-3-opus"
- "mistral.mistral-large-2402-v1:0"
- Note: I didn't add the cohere command R models as langchain doesn't have support for their needed parameters (plus they rank low, so is it a loss?)
In the embeddings section:
- Added a new model "amazon.titan-embed-text-v2:0" with an embedding dimension of 1024.
- Added a "description" field for each embedding model, specifying the embedding dimensions.
Each model has been tested on my local with success.
> Updated bedrock model list

- packages/components/nodes/documentloaders/DocumentStore/DocStoreLoader.ts
Flow crashes when new Document Store Node is used with double quotes https://github.com/FlowiseAI/Flowise/issues/2386
> BugFix #2386: Double quotes are not escaped, flow crashes

- packages/server/src/utils/index.ts
- packages/server/tsconfig.json
This PR fixes the JSON parssing error that `variableValue` contains newlines
```json
{
"text": "a\\nb" 
}
```
> Fix JSON escaping

- packages/components/nodes/memory/DynamoDb/DynamoDb.ts
- packages/components/src/storageUtils.ts
This pull request addresses issue #2466.
Currently, Flowise has four features or components that use AWS services:
- Flowise Storage
- DynamoDB Chat Memory
- AWS Bedrock
- S3 file
However, only AWS Bedrock and S3 file support AWS role-based authentication by making access keys optional. Since the AWS SDK supports seeking credentials from multiple sources, if access keys are not provided during client initialization, it will search for other authentication methods.
This PR makes credentials optional for Flowise Storage and DynamoDB Chat Memory, allowing for role-based authentication.
Role-based authentication is particularly useful when deploying to K8S, as roles can be assumed by pods (Flowise) by configuring a ServiceAccount. It is also one of the preferred methods for granting access to …
> Feature: Support role-based authentication for AWS

- packages/components/src/speechToText.ts
- packages/server/src/services/openai-assistants-vector-store/index.ts
- packages/server/src/services/openai-assistants/index.ts
Fix for error reported on Discord:
toFile() is a helper by openai to create the correct data to send to whisper.
Below is after the fix (disconsider the pt-br thing, I used the wrong ISO):
> Fix for Whisper Error: 'File is not defined' when using Speech to Text

- packages/components/credentials/OpenSearchUrl.credential.ts
- packages/components/nodes/vectorstores/OpenSearch/OpenSearch.ts
Version 1.8.1 included the new OpenSearch credentials with the URL field. This allows to save in a central and secure way the connection credentials for OpenSearch.
But it requires the user to save the username and password hardcoded inside the URL field in the form: `https://user:password@url.com`.
This approach has a few downsides:
- Password is in plan text in the UI, which could lead to security issues if there is an unauthorized access.
- Some people might not know that OpenSearch allows to put the username and password as part of the URL.
My proposal in this PR is to change the OpenSearch credential to have 3 fields:
- URL
- User (optional)
- Password (optional)
and build the final URL inside the OpenSearch component.
> Improve OpenSearchURL credential storing user and password in separate fields from the URL

- packages/server/src/Interface.DocumentStore.ts
this allows a URL to appear in the document store listing when using web scrapers.
added puppeteer and playwright
fixes https://github.com/FlowiseAI/Flowise/issues/2520
> adding url to source for all web scrapers

- CONTRIBUTING-ZH.md
- CONTRIBUTING.md
- docker/.env.example
- packages/server/.env.example
- packages/server/src/commands/start.ts
- packages/server/src/utils/buildChatflow.ts
Discussed in #2533, this PR adds a new env variable `DISABLE_CHATFLOW_REUSE` to allow users to decide if they want to create a new ChatFlow in each interaction or reuse current one when possible.
This is useful for a few reasons:
- Debugging purposes: If a user sees an issue and we think it might be related to caching, we can ask to disable it temporarily and try again.
- Avoid issues with unsupported flows: Flows like the one described in #2533 are not supported by current logic and users might decide to disable the reuse of ChatFlows.
Current implementation adds a new condition to the `ifFlowReusable` function to check for the new env variable `DISABLE_CHATFLOW_REUSE`.
This approach is simple and keeps the `chatflowPool` active for other use cases, like AgentFlow abortion.
Another …
> Feature - Env variable to disable ChatFlow reuse

- docker/Dockerfile
- docker/docker-compose.yml
The Dockerfile wasn't working with the command:
`CMD flowise`
Based on the documentation, to start Flowise, you should use the command "start". In this case, the Dockerfile was updated to use:
ENTRYPOINT ["npx", "flowise", "start"]
Reference:
[get started | Flowise](https://docs.flowiseai.com/getting-started)
> fix: Change the CMD flowise command in Dockerfile to be the same as in the document

- packages/ui/src/ui-component/dialog/ExpandTextDialog.jsx
When testing a JS function from the node, a message with the results should appear below the code view.
Currently there are two issues:
- When JS execution throws an error, the frontend is crashing leading to a full white screen and losing the progress if not saved.
- Code view has a fixed size that doesn't give enough room for the error message to show. User has to scroll to view it. This makes it hard for users to know that there is actually a message with the response being shown and generates confusion even knowing that this happens. 
This PR tackles both issues:
- Fixes crash by transforming the response object to string to be printed on screen.
- Reduces heigh of code view by 180px to give room to response message. Screenshots below show the before and after.
**Before:**
Code view …
> Bugfix - JS function "execute" from node crashing the frontend and response is hidden

- packages/server/src/DataSource.ts
- packages/server/src/database/migrations/mariadb/1693840429259-Init.ts
- packages/server/src/database/migrations/mariadb/1693997791471-ModifyChatFlow.ts
- packages/server/src/database/migrations/mariadb/1693999022236-ModifyChatMessage.ts
- packages/server/src/database/migrations/mariadb/1693999261583-ModifyCredential.ts
- packages/server/src/database/migrations/mariadb/1694001465232-ModifyTool.ts
- packages/server/src/database/migrations/mariadb/1694099200729-AddApiConfig.ts
- packages/server/src/database/migrations/mariadb/1694432361423-AddAnalytic.ts
- packages/server/src/database/migrations/mariadb/1694658767766-AddChatHistory.ts
- packages/server/src/database/migrations/mariadb/1699325775451-AddAssistantEntity.ts
- packages/server/src/database/migrations/mariadb/1699481607341-AddUsedToolsToChatMessage.ts
- packages/server/src/database/migrations/mariadb/1699900910291-AddCategoryToChatFlow.ts
- packages/server/src/database/migrations/mariadb/1700271021237-AddFileAnnotationsToChatMessage.ts
- packages/server/src/database/migrations/mariadb/1701788586491-AddFileUploadsToChatMessage.ts
- packages/server/src/database/migrations/mariadb/1702200925471-AddVariableEntity.ts
- packages/server/src/database/migrations/mariadb/1706364937060-AddSpeechToText.ts
- packages/server/src/database/migrations/mariadb/1707213626553-AddFeedback.ts
- packages/server/src/database/migrations/mariadb/1709814301358-AddUpsertHistoryEntity.ts
- packages/server/src/database/migrations/mariadb/1710832127079-AddLead.ts
- packages/server/src/database/migrations/mariadb/1711538023578-AddLeadToChatMessage.ts
- packages/server/src/database/migrations/mariadb/1711637331047-AddDocumentStore.ts
- packages/server/src/database/migrations/mariadb/1714679514451-AddAgentReasoningToChatMessage.ts
- packages/server/src/database/migrations/mariadb/1766759476232-AddTypeToChatFlow.ts
- packages/server/src/database/migrations/mariadb/index.ts
I created the `mariadb` option to `DataSource.ts` for handling MariaDB.
MariaDB has no `utf8mb4_0900_ai_ci`, so I chosen `utf8mb4_unicode_520_ci` instead.
This is the new config for `MariaDB` as the data source:
```env
DATABASE_TYPE="mariadb"
DATABASE_PORT="3306"
DATABASE_HOST="localhost"
DATABASE_NAME="flowise"
DATABASE_USER="flowise"
DATABASE_PASSWORD="mypassword"
```
As result, the patch is working fine with MariaDB.
> Add data source adapter of MariaDB

- docker/Dockerfile
This draft PR transforms the main Dockerfile to a multistage build. The multistage build allows for any unnecessary files, like npm cache files, to be left outside of the runtime image reducing the final size significantly.
I calculated the following sizes before and after the changes (numbers are approximates):
**Before**
Uncompressed: `~3.2GB`
Compressed: `~0.98GB`
**After**
Uncompressed: `~2.3GB`
Compressed: `~0.67GB`
But this could be optimised even more if we review the packages that are being installed with APK:
`git 
python3 
py3-pip 
make 
g++ 
build-base 
cairo-dev 
pango-dev`
These packages do not seem to be necessary when installing Flowise through npm and I doubt they are actually needed in runtime. I'm not a node expert, but I'd think that any dependencies needed are …
> Improvement - Reduce size of final docker image with multistage build

- .gitignore
Nothing big but those files generated by pnpm usage are not yet in the .gitignore
> Adding pnpm-store to gitignore

- packages/ui/src/ui-component/table/FlowListTable.jsx
As requested by someone in Discord, this PR adds sorting capabilities to the ChatFlow and AgentFlow tables.
Description:
- TableSortLabel used for the view applied to the header row
- Allow the user to sort by `Name` and `Last modified date`, descending and ascending
- Default behavior is sorted by `Last modified date` descending
- When user changes the sort configuration, it is stored in local storage
- Configuration for ChatFlow and AgentFlow is independent
> [Feature] Add sort capabilities to ChatFlow and AgentFlow tables

- packages/components/nodes/documentloaders/Unstructured/UnstructuredFile.ts
When upserting with the API, the uploaded files are of type pdfFile, txtFile, etc. but the code reads only fileObject which is the uploaded file using the button
> Unstructured Upsert bug

- packages/ui/src/views/chatflows/EmbedChat.jsx
This PR adds new feature of Tooltip and autofocus functionality in embed chat.
> Embed Chat configuration updated

- packages/components/nodes/tools/ChatflowTool/ChatflowTool.ts
This PR adds an option to the Chatflow Tool to decide if the conversation with the Chatflow keeps the same session or is independent with each interaction. This is very useful when using it with a Chatflow that has memory, to avoid it.
My use case is the following:
- Chatflow 1: Is a chat bot that answers questions based on RAG, with memory.
- Chatflow 2: Is an agent that uses the Chatflow 1 as a tool and it's instructed to, based on a list of questions and expected answers, ask them to the Chatflow 1 and evaluate each response.
In scenarios like this where repeated independent tasks are executed, memory is not desirable. Chatflow 1 might get confused about what is being asked in each independent task.
> Feature - Add option to start a new session with each interaction with the Chatflow tool

- packages/components/nodes/tools/CustomTool/core.ts
This error occurs when the result returned by CustomTool is of type number.
> Fix `observation?.includes is not a function`

- packages/components/nodes/documentloaders/Cheerio/Cheerio.ts
Hi,
There is a fix for issue https://github.com/FlowiseAI/Flowise/issues/2617. There were two problems. 
Firstly, sometimes cheerioLoader fails to download contnent of page and it returns undefined, so I added assignment of empty arrays if there is undefined. 
Secondly, CheerioWebBaseLoader doesn’t support loading PDF files. It takes a lot to load PDF file and the content is encoded so I believe it shouldn’t be downloaded as Document. So I added condition to avoid downloading PDF files.
I’ve tried it on the same Chatflow as in the issue.
> FIX #2617 Cherio Web Crawler doesn't work with large sites

- packages/server/marketplaces/tools/Perplexity AI Search.json
This pull request adds a new tool named **perplexity_ai_search** to the marketplaces/tools directory. The tool utilizes the Perplexity AI online model for conducting research. The tool is built using the Langchain framework and includes the necessary configurations and a function to interact with the Perplexity AI API.
**Code Added:**
```
{
"name": "perplexity_ai_search",
"framework": "Langchain",
"description": "Useful when conducting research using Perplexity AI online model.",
"color": "linear-gradient(rgb(155,190,84), rgb(176,69,245))",
"iconSrc": "https://raw.githubusercontent.com/AsharibAli/project-images/main/perplexity-ai-icon.svg",
"schema": "[{\"id\":1,\"property\":\"query\",\"description\":\"Query for research\",\"type\":\"string\",\"required\":true}]",
"func": "const fetch = …
```
> Add Perplexity AI Search Tool to Marketplaces/Tools

- packages/components/nodes/vectorstores/MongoDBAtlas/MongoDBAtlas.ts
- packages/components/src/utils.ts
[NODE-6240](https://jira.mongodb.org/browse/NODE-6240)
Hello! 👋🏻 I am adding [`driverInfo`](https://mongodb.github.io/node-mongodb-native/6.8/interfaces/DriverInfo.html) to the MongoClient construction in the MongoDBAtlas component. 
This field is intended for libraries wrapping the driver to push relevant information to the client metadata sent along with the initial handshake during connection creation. This information can be viewed in server logs to assist with debugging the source of a connection issue. It also provides data for determining what combined use cases the driver is supporting ([ex. mongoose](https://github.com/Automattic/mongoose/blob/2d4b8c2995251b8ece99da72a0fe1ba4481c8d18/lib/drivers/node-mongodb-native/connection.js#L295-L298)).
Ideally, I would like to set the …
> feat: add driverInfo to mongodb component

- packages/components/nodes/documentloaders/S3Directory/S3Directory.ts
- packages/components/nodes/documentloaders/S3Directory/s3.svg
This PR introduces a new component which will allow a user to load multiple documents from an S3 bucket. There are optional parameters Server URL and Prefix. The component duplicates the functionality of the filesystem directory document loading component. 
When connecting to MinIO buckets or a local S3 bucket, the Server URL will need to be provided.
When you want to filter only entries under a specific directory you would use the prefix option (hierarchy in s3 is flat so if there was a directoryB in directoryA, you would specify directoryA/directoryB to only load contents of directoryB) This also defaults to recursive loading. Another option can be added to limit that if needed.
Tested with a MinIO bucket containing pdf files in different directories. Verified with no prefix(download …
> S3 Directory Document Loading Component

- packages/ui/src/views/canvas/AddNodes.jsx
This PR is for adding an `autoFocus` on the search field in the `AddNodes` component, so that the input loads focused, and the user can start typing right away.
Fixes #2881
> fix: Autofocus on the add node search input field

- Dockerfile
Fixes the following memory error when building:
`93.14 flowise-components:build: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
93.14 flowise-components:build: ----- Native stack trace -----
93.14 flowise-components:build:
93.26 flowise-components:build: Aborted
93.26 flowise-components:build:  ELIFECYCLE  Command failed with exit code 134.
93.27 flowise-components:build: ERROR: command finished with error: command (/usr/src/packages/components) pnpm run build exited (134)
93.27 flowise-components#build: command (/usr/src/packages/components) pnpm run build exited (134)`
> update Dockerfile to fix broken build (increase node js memory limit)

- packages/components/nodes/documentloaders/Spider/Spider.ts
This updates the Spider tool to include optional additional metadata that can be used when eg. indexing vector DB's
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)
> feat: additional metadata added to Spider tool

- packages/server/src/database/migrations/mariadb/1716300000000-AddTypeToChatFlow.ts
- packages/server/src/database/migrations/mariadb/index.ts
- packages/server/src/database/migrations/mysql/1716300000000-AddTypeToChatFlow.ts
- packages/server/src/database/migrations/mysql/index.ts
- packages/server/src/database/migrations/postgres/1716300000000-AddTypeToChatFlow.ts
- packages/server/src/database/migrations/postgres/index.ts
- packages/server/src/database/migrations/sqlite/1716300000000-AddTypeToChatFlow.ts
- packages/server/src/database/migrations/sqlite/index.ts
1. When new user come in it will always be the last to run.
3. sqlite does not check whether column is created.
1. Modify `1766759476232` to `1716300000000`.
2. Add check whether column exists in sqlite.
> fix migration with wrong unix timestamp

- packages/ui/src/layout/MainLayout/Sidebar/MenuList/NavItem/index.jsx
This pull request addresses vertical alignment issues in the side menu (MuiDrawer component) by making the following improvements:
1. **Vertical Alignment of Side Menu Button Labels**
- Fixed the vertical alignment of labels, such as 'Agentflows', which were not centered within their containers.
- Applied automatic vertical margins to `<ListItemText>` and added a 4px vertical margin to the primary text element `<Typography>` to maintain existing margins.
2. **Vertical Alignment of Side Menu BETA Chips**
- Corrected the vertical alignment of 'BETA' chips in the side menu.
- Ensured that the chips are consistently centered regardless of the presence of captions in the corresponding text labels.
3. **Adjust Margin for Secondary Labels (a.k.a., captions)**
- Added `mt: -0.6` to the secondary …
> Chore/Vertically center text labels in MuiDrawer side menu

- packages/server/src/controllers/predictions/index.ts
Hi Flowise team, 
I discovered that after configuring `allowedDomains` (as dynamic CORS) for a chatflow, It checks my origin header even if it is undefined. The request might be sent from a proxy server or postman and usually sends requests with undefined origin.
The error I got when requesting to `/api/v1/prediction` from postman or curl was:
```
{
"statusCode": 500,
"success": false,
"message": "Invalid URL",
"stack": {}
}
```
> fix: ignore `allowedOrigins` config for undefined `origin` header to ensure correct CORS behavior

- packages/components/nodes/embeddings/AzureOpenAIEmbedding/AzureOpenAIEmbedding.ts
In the Azure OpenAI Embeddings node, I added a BasePath item to the endpoint like the Azure OpenAI node. 
- #3048
> [FEATURE] Add "base path" to Azure OpenAI embeddings node

- packages/server/src/index.ts
add fixes to prevent bypassing api url
> Bugfix/Auth URL Bypass

- packages/server/src/utils/buildChatflow.ts
- packages/server/src/utils/index.ts
This PR enhances the variable resolution process in the flow building mechanism, particularly focusing on the `buildFlow` and `getVariableValue` functions.
1. **Flow Options Enhancement**
- Added a new `options` object in the `buildFlow` function:
```typescript
const options: ICommonObject = {
chatflowid,
chatId,
sessionId,
chatHistory
}
```
2. **Variable Resolution Improvements**
- Updated `resolveVariables` and `getVariableValue` functions to accept and utilize the new `options` parameter.
3. **Flow-specific Variable Support**
- Implemented handling for variables starting with `$flow.` in the `getVariableValue` function:
```typescript
if (variableFullPath.startsWith('$flow.') && options) {
const variableValue = get(options, variableFullPath.replace('$flow.', ''))
if (variableValue) { …
```
> Add $flow to Variable Resolution in Flow Building Process

- packages/server/src/utils/index.ts
Adjusting the type of IfElseFunction will cause not work. I found that it is caused by hard coding here.
> Avoid hard-coding returnFalse and returnTrue handle fetching.

- packages/components/nodes/sequentialagents/ToolNode/ToolNode.ts
- packages/components/src/Interface.ts
Allows the use of `$flow.state.var` inside the custom tool by passing the state in the ToolNode:
for example:
we have the output 
when we use the following function in the custom tool node:  ```return successfully called tool ${$flow.state.test}`;```
This is inlie with the behaviour mentionsed in the `How to Use Function`
Previously we were getting the following an error:
Ps: I am only passing the state without the messages since we are already using the toolNode to get the functions to calls. I dont see why we would need the messages in the tool itself but I could be shortsighted on this.
> Passing state to tool so that we can use them in custom tools

- packages/ui/src/views/chatflows/ShareChatbot.jsx
> Feature/Hide or Show agent messages for share chatbot

- packages/components/nodes/utilities/CustomFunction/CustomFunction.ts
It is easier to handle some complex logic with CustomFunction, but it lacks the ability to directly call existing tools, 
so this PR is added to support this feature, reuse existing Chatflows, tools, etc.
> feat: add support for calling tools in CustomFunction

- docker/Dockerfile
- docker/docker-compose.yml
This was driving me crazy when building Flowise as it would give a warning that the casing was not consistent.
> Correct "as" casing

- packages/ui/src/ui-component/dialog/SaveChatflowDialog.jsx
The save flow dialog has only one input and it is the primary one, there is no need for an extra click to be able to set the title. With the autofocus on the user can start writing right away.
I think that in this case the eslint rule is properly disabled and it aligns with even [one](https://brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/) of the refs listed in the jsx-a11y/no-autofocus
Here you can find two small gifs showing the contribution of this PR.
Before
After
> feat: enable autofocus to the `new chatflow title` to improve usability

- packages/ui/src/views/canvas/CanvasHeader.jsx
This simple event handler improves the usability of the UI by avoiding having to use the mouse to save or discard title changes
Here you can see small example of the contribution of this PR
Before
After
> feat: save Chatflow title when the `ENTER` key is pressed or discard upon `ESC` is pressed

- packages/ui/src/ui-component/cards/MainCard.jsx
By default MainCard wrappers like NodeCardWrapper and CardWrapper add a a solid border of 1px, but if the `MainCard.border` prop is used (`false`) the border prop was wrongly set to a boolean instead of string
Here is an example of the fixed warning
> fix: warning when passing a boolean to border property of a Card

- packages/ui/src/layout/MainLayout/ViewHeader.jsx
> feat: add shortcut text hint to the search field

- packages/ui/src/ui-component/switch/Switch.jsx
The problem was that in the useEffect hook the plain value was used without validation like in useState
> fix: warning when a non-boolean values was used to set `checked` prop of a SwitchInput component

- packages/components/models.json
> The gemini-1.5-pro and gemini-1.5-flash model codes will default to use the -002 versions automatically on October 8, 2024. You can continue to use the previous model version by using the gemini-1.5-pro-001 or gemini-1.5-flash-001 model codes.
Source: https://ai.google.dev/gemini-api/docs/models/gemini
> Updating models.json with new Gemini models

- packages/components/nodes/vectorstores/MongoDBAtlas/MongoDBAtlas.ts
Summary:
This pull request introduces changes that enable the use of filters in the MongoDB vector search retriever, similar to how it’s done in Pinecone.
Description:
• These changes will allow the implementation of filters in the MongoDB Vector Search Retriever, aligning with the capabilities provided by Pinecone.
• When creating an Atlas Vector Search to index the embedding field, it’s important to also add the filters you want to use, as demonstrated in the MongoDB documentation: [MongoDB Atlas Vector Search - Create Index](https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-type/#std-label-avs-create-index).
Points to consider:
• Ensure that when configuring the Atlas Vector Search for your application, you define both the embedding field and any necessary filters …
> Enable Filters in MongoDB Vector Search Retriever

- packages/components/nodes/agents/AirtableAgent/AirtableAgent.ts
- packages/components/nodes/agents/CSVAgent/CSVAgent.ts
- packages/server/marketplaces/chatflows/CSV Agent.json
* In multiple files the Airtable Agent description had the word "to" duplicated like this "Agent used to to answer queries on Airtable table". 
* Removed the duplicate
> Fix duplicate words in Airtable Agent description

- packages/server/src/database/migrations/mariadb/1725629836652-AddCustomTemplate.ts
Fixes a problem when deploying with MariaDB database type.
`Migration "AddCustomTemplate1725629836652" failed, error: Unknown collation: 'utf8mb4_0900_ai_ci'`
> fix: unknown collate in AddCustomTemplate migration for MariaDB

- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
- Stop Sequence added into OpenAI params
> Refactor ChatOpenAI_ChatModels to include stopSequence parameter

- packages/server/src/database/migrations/mariadb/1715861032479-AddVectorStoreConfigToDocStore.ts
- packages/server/src/database/migrations/mariadb/index.ts
Add missing MariaDB migration for vector store configuration in document store
> fix: Add missing migration in MariaDB

- docker/.env.example
- packages/server/.env.example
- packages/server/package.json
- packages/server/src/index.ts
- pnpm-lock.yaml
With central configuration of global agent via environment variables, the proxy agent is included in all node-fetch requests without any code changes and thus it is no longer necessary to implement the proxy URL in each ChatModel. Currently, the ProxyUrl is implemented in ChatOpenAI_ChatModels and as an example is still required in AzureChatOpenAI_ChatModels. The existing proxy mechanism would continue to work if required, because the global agent can be deactivated by a missing environment variable.
- Added global-agent as central Global HTTP/HTTPS proxy configurable sing environment variable
-  https://www.npmjs.com/package/global-agent
- Server-Bootstrap on index.js 
- import global-agent/bootstrap
- added dep in package.json 
- global-agent: "^3.0.0
> Support global-agent for central proxy configuration 

- packages/components/nodes/documentloaders/S3File/README.md
- packages/components/nodes/documentloaders/S3File/S3File.ts
- packages/components/nodes/documentloaders/Unstructured/README.md
- packages/components/nodes/documentloaders/Unstructured/Unstructured.ts
- packages/components/nodes/documentloaders/Unstructured/UnstructuredFile.ts
- packages/components/nodes/documentloaders/Unstructured/UnstructuredFolder.ts
Hi Flowise,
When having an `UNSTRUCTURED_API_URL` set, we don't want this params as required in loaders.
This PR aims to:
> [Usntructured loaders] Make Unstructured API URL optional when environment variable is present

- packages/components/nodes/chatmodels/AzureChatOpenAI/AzureChatOpenAI.ts
- packages/components/nodes/chatmodels/AzureChatOpenAI/README.md
- packages/components/nodes/embeddings/AzureOpenAIEmbedding/AzureOpenAIEmbedding.ts
- packages/components/nodes/embeddings/AzureOpenAIEmbedding/README.md
- packages/components/nodes/llms/Azure OpenAI/AzureOpenAI.ts
- packages/components/nodes/llms/Azure OpenAI/README.md
Hi Flowise,
This PR makes Azure OpenAI credentials optional when corresponding env var (managed by langchain) are set.
> [Azure OpenAI] Make credentials optional when env variables are set

- packages/components/nodes/embeddings/AzureOpenAIEmbedding/AzureOpenAIEmbedding.ts
* Set azureOpenAIBasePath to undefined if empty to enforce usage of env variable AZURE_OPENAI_BASE_PATH in @langchain+openai@0.0.30_encoding@0.1.13_langchain@0.2.11/node_modules/@langchain/openai/dist/embeddings.cjs
> Azure OpenAI Embeddings ignores env variable AZURE_OPENAI_BASE_PATH

- packages/ui/vite.config.js
The proxy settings currently apply to all URLs that start with /api, including /apikey. This causes unintended routing where /apikey is proxied, resulting in a 404 error or incorrect loading behavior. The solution restricts proxy settings to exact /api routes or those that follow the /api/ pattern, allowing /apikey and similar routes to be handled by the frontend.
> fix(proxy): restrict proxy to exact /api routes only

- packages/ui/src/views/chatflows/EmbedChat.jsx
- packages/ui/src/views/chatmessage/ChatInputHistory.js
- packages/ui/src/views/chatmessage/ChatMessage.jsx
- Works like Linux shell
- History limited to 10 messages
Loom video showing functionality: https://www.loom.com/share/e7d557da0759454184f44ccf7fcd9c63?sid=7f563c6f-7bd4-45e5-9b80-fe269aabb867
> Add Up and Down arrow functionality to chat messages

- packages/components/credentials/FireCrawlApi.credential.ts
- packages/components/nodes/documentloaders/FireCrawl/FireCrawl.ts
Minor change for supporting [self-hosted FireCrawl endpoint](https://docs.firecrawl.dev/contributing/self-host)
(By adding a missing param for `Api Url`)
Works fine for the  ver.0 API Scrape func.
> feat: Add Custom Api Url Param for Self-hosted FireCrawl endpoint

- packages/components/nodes/tools/RetrieverTool/RetrieverTool.ts
Extended Retriever Tool to support metadata filter based on the object stored in agent state.
> Feature/Add support for state-based metadata filter to Retriever Tool

- packages/api-documentation/src/yml/swagger.yml
- packages/components/nodes/documentloaders/Unstructured/UnstructuredFile.ts
- packages/server/src/Interface.DocumentStore.ts
- packages/server/src/controllers/documentstore/index.ts
- packages/server/src/routes/documentstore/index.ts
- packages/server/src/services/documentstore/index.ts
- packages/server/src/utils/createAttachment.ts
- packages/ui/src/api/documentstore.js
- packages/ui/src/routes/MainRoutes.jsx
- packages/ui/src/ui-component/cards/DocumentStoreCard.jsx
- packages/ui/src/views/docstore/DocumentStoreDetail.jsx
- packages/ui/src/views/docstore/DocumentStoreStatus.jsx
- packages/ui/src/views/docstore/LoaderConfigPreviewChunks.jsx
- packages/ui/src/views/docstore/ShowStoredChunks.jsx
- packages/ui/src/views/docstore/VectorStoreConfigure.jsx
- /document-store/upsert/:id
- /document-store/refresh/:id
> Feature/Add new doc store upsert and refresh API

- packages/ui/src/views/chatflows/EmbedChat.jsx
This PR consolidates, expands, and completes the capabilities for the embedded chat widget, providing full configuration support for all modes and aligning with all current config.
Key changes include:
*   Consolidation of theme configurations into a single `defaultThemeConfig`.
*   Added missing configuration options to match all current capabilities.
*   Corrected fullpage chat window sizing to occupy 100% of the viewport.
> Enhanced Chat Embed Configuration View

- packages/server/src/utils/buildAgentGraph.ts
- packages/server/src/utils/buildChatflow.ts
Simple Flow: Follow part of video on sequential flows until 9:15 where LLM Node setup is complete and connected to an end node.
https://www.youtube.com/watch?v=3ZmBq8_4vCs&list=PL4HikwTaYE0H7wBxhvQqxYcKOkZ4O3zXh
Stacktrace:
Error: Cannot read properties of undefined (reading 'label') flowise:dev: at buildAgentGraph (\Flowise\packages\server\dist\utils\buildAgentGraph.js:402:19) flowise:dev: at async utilBuildAgentResponse (\Flowise\packages\server\dist\utils\buildChatflow.js:435:31) flowise:dev: at async utilBuildChatflow (\Flowise\packages\server\dist\utils\buildChatflow.js:198:20) flowise:dev: at async createAndStreamInternalPrediction (\Flowise\packages\server\dist\controllers\internal-predictions\index.js:33:29) flowise:dev: 2024-11-26 13:50:21 [ERROR]: [server]: Error: Error …
> Fix 'label' undefined errors for sequential agents

- packages/components/nodes/vectorstores/Milvus/Milvus.ts
> [Bugfix] Milvus search error

- packages/components/nodes/memory/AgentMemory/mysqlSaver.ts
- packages/components/nodes/memory/AgentMemory/pgSaver.ts
Fix new Agent Memory database option MySQL creating multiple connections to database throughout chat messages
> fix: change data source lifecycle on agent memory mysql saver

- packages/components/models.json
- packages/components/package.json
Add Meta's latest Llama 3.3 70B models to groqChat options:
- llama-3.3-70b-versatile: New versatile model for general tasks
- llama-3.3-70b-specdec: Specialized model for specific tasks
These models offer comparable quality to Llama 3.1 405B at 1/5th the size, with improvements in:
- Reasoning and math capabilities
- General knowledge tasks
- Instruction following
- Tool use and JSON outputs
- Code generation and feedback
> feat(models): add Llama 3.3 70B models to groqChat

- packages/server/src/database/migrations/mariadb/1726666318346-AddFollowUpPrompts.ts
Fix wrong table name in AddFollowUpPrompts migration for MariaDB
> fix: followUpPrompts migration for MariaDB

- packages/components/nodes/chatmodels/ChatIBMWatsonx/ChatIBMWatsonx.ts
Closes #3683 
Added the following fields to chat watsonx:
- Frequency Penalty
- Log Probs
- N
- Presence Penalty
- Top P
> Add missing inputs

- packages/components/nodes/chatmodels/ChatGoogleVertexAI/ChatGoogleVertexAI.ts
@HenryHengZJ - I've added Custom Model feature to ChatGoogleVertexAI node based on this example https://github.com/FlowiseAI/Flowise/pull/3088.
Tested and works great.
Hope that works / helps test experimental models released on Vertex!
> Vertex Gemini Custom Model Changes

- packages/server/src/utils/getRunningExpressApp.ts
If the database closes the connection during initialization, the app server continues to work with uninitialized properties.
```
[server]: Error during Data Source initialization: Connection lost: The server closed the connection.
QueryFailedError: Connection lost: The server closed the connection.
[server]: Flowise Server is listening at :3000
...
[server]: Error: Cannot read properties of undefined (reading 'sendTelemetry')
TypeError: Cannot read properties of undefined (reading 'sendTelemetry')
```
https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/index.ts#L82
Current code only checks for _nodesPool_ initialization but there are still actions that can fail after the _nodesPool_ is initialized. This PR addresses this issue by checking if the telemetry is successfully …
> fix: Error Cannot read properties of undefined (reading 'sendTelemetry')

- packages/components/nodes/sequentialagents/commonUtils.ts
There is an issue in 2.2.1 where using AnthropicChat in an agent flow with a tool was causing an error because it wasn't setup to handle an array.
> [BUGFIX] Fix value.startsWith is not a function error

- packages/ui/src/routes/MainRoutes.jsx
- packages/ui/src/views/assistants/custom/CustomAssistantConfigurePreview.jsx
- packages/ui/src/views/docstore/DocumentStoreDetail.jsx
- packages/ui/src/views/docstore/LoaderConfigPreviewChunks.jsx
- packages/ui/src/views/docstore/ShowStoredChunks.jsx
- packages/ui/src/views/docstore/VectorStoreConfigure.jsx
- packages/ui/src/views/docstore/VectorStoreQuery.jsx
The solution that was in the release caused an error in vectostoreconfig if the flowise runned not in the root URL, but in a subpath. I propose an option with the correct receipt of parameters that are provided by the route.
> fix: getting docId, storeId parameters

- packages/ui/src/hooks/useSearchShortcut.jsx
- packages/ui/src/layout/MainLayout/ViewHeader.jsx
useSearchShorcut ➡️ useSearchShor`t`cut
> fix(ui): fix typo

- packages/components/nodes/agents/AirtableAgent/AirtableAgent.ts
- packages/components/nodes/agents/CSVAgent/CSVAgent.ts
- packages/components/nodes/agents/ConversationalRetrievalToolAgent/ConversationalRetrievalToolAgent.ts
- packages/components/nodes/agents/LlamaIndexAgents/AnthropicAgent/AnthropicAgent_LlamaIndex.ts
- packages/components/nodes/agents/LlamaIndexAgents/OpenAIToolAgent/OpenAIToolAgent_LlamaIndex.ts
- packages/components/nodes/agents/ReActAgentLLM/ReActAgentLLM.ts
- packages/components/nodes/agents/ToolAgent/ToolAgent.ts
- packages/components/nodes/agents/XMLAgent/XMLAgent.ts
- packages/components/nodes/chains/ApiChain/GETApiChain.ts
- packages/components/nodes/chains/ApiChain/OpenAPIChain.ts
- packages/components/nodes/chains/ApiChain/POSTApiChain.ts
- packages/components/nodes/chains/MultiPromptChain/MultiPromptChain.ts
- packages/components/nodes/chains/MultiRetrievalQAChain/MultiRetrievalQAChain.ts
- packages/components/nodes/chains/RetrievalQAChain/RetrievalQAChain.ts
- packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
- packages/components/nodes/chains/VectorDBQAChain/VectorDBQAChain.ts
- packages/components/nodes/multiagents/Worker/Worker.ts
- packages/components/nodes/sequentialagents/Agent/Agent.ts
hey, 
I cleanup some debugging conditions, to make it unified in style :'D
> clean(components): is debug boolean syntax shorthand

- packages/components/src/Interface.ts
- packages/components/src/followUpPrompts.ts
- packages/ui/src/ui-component/extended/FollowUpPrompts.jsx
Adds support for the Groq language model to the follow-up prompts feature. 
Integration of Groq language model:
* Updated the `FollowUpPromptProvider` enum to include `GROQ`.
* Integrated Groq-specific logic in the `generateFollowUpPrompts` function.
UI updates for Groq support:
* Updated `FollowUpPromptProviders` and `followUpPromptsOptions` to include Groq-specific configurations and icons.
> Feature/Add Groq for followup prompts

- packages/components/nodes/memory/RedisBackedChatMemory/RedisBackedChatMemory.ts
- packages/components/nodes/memory/UpstashRedisBackedChatMemory/UpstashRedisBackedChatMemory.ts
TTL didn't mention that it was seconds, which differs from other Redis configs as well. 
Simple change to clear that up 👍
> Slight Redis Memory description change to include units

- packages/api-documentation/src/yml/swagger.yml
- packages/server/src/Interface.DocumentStore.ts
- packages/server/src/controllers/documentstore/index.ts
- packages/server/src/index.ts
- packages/server/src/routes/documentstore/index.ts
- packages/server/src/services/assistants/index.ts
- packages/server/src/services/documentstore/index.ts
- packages/server/src/utils/constants.ts
- packages/server/src/utils/upsertVector.ts
- packages/ui/src/api/documentstore.js
- packages/ui/src/views/chatflows/APICodeDialog.jsx
- packages/ui/src/views/docstore/DocStoreAPIDialog.jsx
- packages/ui/src/views/docstore/DocumentStoreDetail.jsx
- packages/ui/src/views/vectorstore/VectorStoreDialog.jsx
- add a new property `metadata` to upsert API
- add a new property `replaceExisting` to upsert API
- add View API on UI
- update swagger
> Feature/update upsert API

- packages/components/src/handler.ts
Hi,
This PR provides a small fix (reported by a Flowise and Lunary user) where the user messages content were not always reported correctly to Lunary.
Thanks in advance!
> Lunary: fix user messages

- packages/server/src/utils/logger.ts
This PR solves the issue mentionned on #3899, The issue is that when trying to plug any S3 provider other than amazon aws, the server startup fails in dns request (check the issue for more info).
This pr solves the issue by using the custom s3 endpoint present in the env variables.
> fix: Fixing logger for custom S3 stream

- packages/components/nodes/agents/ConversationalAgent/ConversationalAgent.ts
- packages/components/nodes/agents/ConversationalRetrievalToolAgent/ConversationalRetrievalToolAgent.ts
- packages/components/nodes/agents/ToolAgent/ToolAgent.ts
- packages/components/nodes/agents/XMLAgent/XMLAgent.ts
- packages/components/nodes/chains/ConversationChain/ConversationChain.ts
- packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts
- packages/components/nodes/prompts/ChatPromptTemplate/ChatPromptTemplate.ts
- packages/components/nodes/prompts/PromptLangfuse/PromptLangfuse.ts
- packages/components/nodes/prompts/PromptTemplate/PromptTemplate.ts
- packages/components/nodes/retrievers/PromptRetriever/PromptRetriever.ts
- packages/components/nodes/sequentialagents/Agent/Agent.ts
- packages/components/nodes/sequentialagents/ConditionAgent/ConditionAgent.ts
- packages/components/nodes/sequentialagents/LLMNode/LLMNode.ts
- packages/components/src/utils.ts
- packages/ui/src/utils/genericHelper.js
- packages/ui/src/views/assistants/custom/CustomAssistantConfigurePreview.jsx
Bug: Currently when you are trying to ask LLM to output a JSON by giving a few examples in the prompt, langchain/flowise by default will get everything enclosed in curly brackets as variables. Therefore, it will incorrectly identify the JSON examples as variables.
https://github.com/FlowiseAI/Flowise/issues/968
Fix: Identify if there is a colon `:` within the curly brackets, if yes, we will not extract the value as variable.
> Bugfix/Escape JSON in Prompt Message

- packages/components/models.json
Update model list for Deepseek chat: Deepseek now no longer has model `deepseek-coder`, new model `deepseek-reasoner`
> Update model names for deepseek components

- packages/ui/src/ui-component/extended/RateLimit.jsx
Current link to Rate Limit documentation is incorrect: 
https://docs.flowiseai.com/rate-limit
Corrected to:
https://docs.flowiseai.com/configuration/rate-limit
> Update RateLimit.jsx - link to documentation incorrect

- packages/components/src/utils.ts
The normalizeURL function was incorrectly removing the port from URLs.
- Explicitly include the port if it's present (`urlObj.port`)
- Prevents unintended behavior where ports (e.g., `:3000`) were stripped
Before:
normalizeURL("http://example.com:3000/path?query=1") → "example.com/path?query=1" (port missing)
After:
normalizeURL("http://example.com:3000/path?query=1") → "example.com:3000/path?query=1" (port retained)
> Fix: Ensure normalizeURL retains port number

- packages/ui/src/views/docstore/DeleteDocStoreDialog.jsx
Added clarification that data will also be removed from the record manager.
Before: 
"Remove data from vector store"
After:
"Remove data from vector store and record manager"
Note: this dialog box only appears when a record manager exists in the doc store. If it's intended to be shown regardless of whether a record manager exists, updates will be needed.
> Update DeleteDocStoreDialog.jsx - added clarification that data will also be removed from the record manager.

- packages/components/nodes/embeddings/JinaAIEmbedding/JinaAIEmbedding.ts
* Add support for Jina [Late Chunking](https://github.com/jina-ai/late-chunking)
* Switch default Jina embedding from jina-embeddings-v2-base-en to jina-embeddings-v3, which is the newer recommended embedding. Also supports multilingual text.
jina-embeddings-v3 support Late Chunking:
`Apply the late chunking technique to leverage the model's long-context capabilities for generating contextual chunk embeddings.`
> Late Chunking support for Jina Embeddings

- packages/components/models.json
- packages/components/nodes/chatmodels/AzureChatOpenAI/AzureChatOpenAI.ts
- packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts
Several small adjustments for o3-mini
**Update ChatOpenAI.ts - corrected reasoning description and default**
- Description for reasoning effort only mentioned o1. Added o3.
- Changed reasoning effort default to medium as this is OpenAI's default / what users will most likely expect (https://platform.openai.com/docs/guides/reasoning)
**Update AzureChatOpenAI.ts - corrected reasoning description and default**
- Description for reasoning effort only mentioned o1. Added o3.
- Changed reasoning effort default to medium as this is OpenAI's default / what users will most likely expect (https://platform.openai.com/docs/guides/reasoning)
**Update models.json - add specific model ID for o3-mini**
- Added o3-mini-2025-01-31
- Updated "o3-mini" label to "o3-mini (latest)"
This allows the user to …
> o3-mini Adjustments.

- packages/ui/src/views/tools/PasteJSONDialog.jsx
- packages/ui/src/views/tools/ToolDialog.jsx
Added a new feature to make it easier to add input schema to custom tools by pasting JSON directly.
- Added "Paste JSON" button next to "Add Item" in the Tool Dialog
- Created new PasteJSONDialog component with JSON code editor
- Added JSON validation and error handling
- Included example JSON template for reference
1. Click "Paste JSON" button in the Input Schema section
2. Either paste your JSON or click "See Example" to see the format
3. Click Confirm to add the properties to the grid
- Tested JSON validation
- Tested example template
- Tested error handling
- Tested dark/light theme support
https://github.com/FlowiseAI/Flowise/issues/4052
> Add Paste JSON Schema Functionality to Custom Tools

- packages/ui/src/views/docstore/LoaderConfigPreviewChunks.jsx
fix for issue #3882
Now user can set a name for each documentLoader that they upload. this will make it easy to track them from the dashboard
changes - 
view in the dashboard(third entry) -
> now user can name each document loader for ease of tracking

- packages/components/nodes/retrievers/ExtractMetadataRetriever/ExtractMetadataRetriever.ts
- packages/components/nodes/retrievers/HydeRetriever/HydeRetriever.ts
- packages/components/nodes/retrievers/MultiQueryRetriever/MultiQueryRetriever.ts
- packages/components/nodes/retrievers/RRFRetriever/ReciprocalRankFusion.ts
- packages/components/nodes/retrievers/SimilarityThresholdRetriever/SimilarityThresholdRetriever.ts
> Fix vector store filter not work

- packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts
- packages/components/nodes/tools/OpenAPIToolkit/OpenAPIToolkit.ts
- packages/components/nodes/tools/OpenAPIToolkit/core.ts
The PR proposes to:
1. Allow OpenAI assistant to call several tools in the same run. This is quite common when the assistant decides to call a second tool after the first one
2. The OpenAPI Toolkit now supports a "x-strict": true  attribute for an action. This creates a function with "strict mode".
The "strict mode" is described here: https://openai.com/index/introducing-structured-outputs-in-the-api/ , https://platform.openai.com/docs/guides/structured-outputs 
Basically it allows to drastically reduce hallucination problems while generating tool calls.
The strict mode has the problem that only a subset of the json spec is supported.
One of the caveats is that all fields must be required. So the workaround is to use an "anyOf" schema with the type null.
For example if we want to make the …
> Several features for OpenAPI toolkit and OpenAI Assistants

- packages/server/src/middlewares/errors/index.ts
- packages/server/src/utils/buildChatflow.ts
When navigating between screens in Flowise, an unhandled rejection error occurs:
```bash
TypeError: Cannot read properties of undefined (reading 'streaming')
at errorHandlerMiddleware (/usr/src/packages/server/dist/middlewares/errors/index.js:14:19)
at Layer.handle_error (/usr/src/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/usr/src/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:326:13)
at /usr/src/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:286:9
at Function.process_params (/usr/src/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:346:12)
at next (/usr/src/node_modules/.pnpm/express@4.18.3/node_modules/express/lib/router/index.js:280:10)
at …
```
> Fix for node-crashing "undefined (reading 'streaming')" error

- packages/server/src/utils/logger.ts
This PR solves issue #3997 by making environment credentials optional for S3 logger, so they can be taken from different alternative sources like K8S service accounts.
> [Fix] Change S3 logger to accept more authorization methods for AWS

- packages/ui/src/views/assistants/openai/AssistantDialog.jsx
This PR adds support for OpenAI's new GPT-4.5-preview model in the OpenAI Assistant Dialog.
- Added GPT-4.5-preview to the list of available models in the Assistant Dialog
OpenAI recently announced GPT-4.5-preview as their latest model with improved capabilities:
https://openai.com/index/introducing-gpt-4-5/
https://community.openai.com/t/gpt-4-5-is-live-in-the-api/1131571
- Verified that the model appears in the dropdown list, and is working fine
- Confirmed that it can be selected when creating or editing an assistant
I didn't include `o1` and `o3-mini` in the Dialog because these models don't support parameters such as Assistant Temperature or Top P.
> Add support for GPT-4.5-preview model in OpenAI Assistant Dialog

- packages/components/src/storageUtils.ts
- packages/components/src/utils.ts
- packages/server/src/utils/index.ts
- packages/server/src/utils/logger.ts
Fix invalid credentials:
```
2025-03-11 21:25:25 [ERROR]: unhandledRejection: Resolved credential object is not valid
Error: Resolved credential object is not valid
at _SignatureV4S3Express.validateResolvedCredentials (/usr/src/node_modules/.pnpm/@smithy+signature-v4@2.1.4/node_modules/@smithy/signature-v4/dist-cjs/index.js:440:13)
at _SignatureV4S3Express.signRequest (/usr/src/node_modules/.pnpm/@smithy+signature-v4@2.1.4/node_modules/@smithy/signature-v4/dist-cjs/index.js:365:10)
Error: Resolved credential object is not valid
at _SignatureV4S3Express.validateResolvedCredentials (/usr/src/node_modules/.pnpm/@smithy+signature-v4@2.1.4/node_modules/@smithy/signature-v4/dist-cjs/index.js:440:13)
at _SignatureV4S3Express.signRequest …
```
> Bugfix/S3 Credentials

- packages/components/nodes/recordmanager/PostgresRecordManager/PostgresRecordManager.ts
- packages/components/nodes/recordmanager/PostgresRecordManager/README.md
- packages/components/nodes/recordmanager/PostgresRecordManager/utils.ts
- packages/components/nodes/vectorstores/Postgres/Postgres.ts
- packages/components/nodes/vectorstores/Postgres/README.md
- packages/components/nodes/vectorstores/Postgres/driver/Base.ts
- packages/components/nodes/vectorstores/Postgres/driver/TypeORM.ts
- packages/components/nodes/vectorstores/Postgres/utils.ts
Add SSL option to vector store and record manager to be consistent with the postgres database driver. Most commercial postgres implementation will require us to use SSL.
> feat: Add SSL configuration option for Postgres connections

- packages/server/src/utils/buildChatflow.ts
fixes the retrieval of agent chat history from the API. 
The issue was caused by referencing the incorrect input key (memory instead of agentMemory) in getChatHistory. This update ensures that agent memory is correctly accessed, preventing chat history from being lost or incorrectly fetched.
Changes:
•	Updated the input reference from memory to agentMemory in buildChatflow.ts.
•	Ensured that when agentMemory is not present, the function returns prependMessages instead of an empty array.
> Fix Agent Chat History Retrieval

- packages/components/src/Interface.ts
- packages/components/src/followUpPrompts.ts
- packages/ui/src/ui-component/extended/FollowUpPrompts.jsx
When using Ollama for the follow-up prompts, you sometimes need to specify a different baseURL instead of http://127.0.0.1:11434
This is especially usefull when:
Ollama is not used in the Chatflow but you still want to use it for follow-up prompts.
Flowise is running in Docker
> Add an Ollama baseUrl in chatflow configuration for Follow-up prompts

- packages/components/nodes/documentloaders/Github/Github.ts
**Feature**
Github Documentloader now supports fetching repos from custom github installations. 
**Details**:
Custom installations are often used in enterprises. It is now possible to set a custom baseUrl and apiUrl which is required by underlying langchain community loader. See https://v03.api.js.langchain.com/interfaces/_langchain_community.document_loaders_web_github.GithubRepoLoaderParams.html
> feat: Enterprise Github

- packages/components/nodes/vectorstores/Postgres/Postgres.ts
in the output config for the Postgres Vector Store for the Vector Store mode the getBaseClasses(VectorStore) is returning an empty array preventing the Postgres Vector Store to connect as a vector store to subsequent nodes that are accepting a Vector Store input. Ref (https://github.com/FlowiseAI/Flowise/issues/4206)
> [fix 4206]: fix the empty array return for getBaseClasses when using typeorm driver and not the PGVectorStore

- packages/components/nodes/memory/Mem0/Mem0.ts
**Description:**
This PR enhances the Mem0 memory node by adding a new toggle option: "Use Flowise Chat ID".
*   **When Enabled:** The node will ignore the hardcoded "User ID" input field and use the internal Flowise `chatId` (session ID) as the `user_id` for all Mem0 operations (saving context, loading variables, clearing memory).
*   **When Disabled (Default):** The node behaves as before, using the value provided in the "User ID" input field for Mem0 operations.
**Changes:**
*   Added a "Use Flowise Chat ID" boolean input toggle to the Mem0 node UI.
*   Updated internal logic (`getEffectiveUserId`) to select the correct ID (Flowise `chatId` or the input field value) based on the toggle state.
*   The "User ID" input field is now only strictly required if the "Use Flowise Chat ID" …
> feat(Mem0): Add option to use Flowise Chat ID

- packages/components/src/utils.ts
- packages/server/.env.example
- packages/server/src/utils/index.ts
Also accounts for existing users using AWS Secrets Manager to store credentials data.
> Update how credential data is saved in db when using aws secrets manager

- packages/components/nodes/chatmodels/ChatGoogleGenerativeAI/FlowiseChatGoogleGenerativeAI.ts
This PR fixes the 400 Bad Request errors when using function calling with Gemini API when MCP tools are used. The main issue was that some properties in the tool schemas were missing explicit type definitions when converting from Zod schemas to Gemini's function declarations format.
- Enhanced `zodToGeminiParameters` function to properly infer types
- Added explicit handling for enum types
- Improved type inference based on property characteristics
- Added fallback to string type when type cannot be inferred
None. This is a backward compatible enhancement to the existing functionality.
> Fix(FlowiseChatGoogleGenerativeAI): 400 Bad Request errors from Gemini API when converting tool schemas - MCP tools.

- packages/server/src/controllers/feedback/index.ts
- packages/server/src/services/feedback/validation.ts
- Introduced validation functions for feedback creation and update in the new validation service. 
- Updated feedback controller to utilize these validation functions before processing requests.
> feat(feedback): add validation for feedback creation and update

- packages/components/nodes/memory/MongoDBMemory/MongoDBMemory.ts
Adding chat history timestamp in mongodb for timeseries data monitoring.
> add history chat timestamp in mongodb

- packages/components/models.json
- packages/ui/src/views/assistants/openai/AssistantDialog.jsx
This PR adds support for OpenAI's new GPT-4.1 series models in the OpenAI Assistant Dialog. The following models have been added:
- `gpt-4.1`
- `gpt-4.1-mini`
- `gpt-4.1-nano`
- Added new GPT-4.1 series models to the available models list in AssistantDialog.jsx
- Updated models.json to include the new model options
- Positioned the new models at the top of the list to indicate they are the latest additions
- Verified that the new models appear in the dropdown list
- Confirmed that they can be selected when creating or editing an assistant
- Ensured existing functionality remains unchanged
These new models represent OpenAI's latest advancements in their model lineup, offering improved capabilities and performance for different use cases:
- `gpt-4.1`: Flagship GPT model for complex tasks
- …
> feat: Add GPT-4.1 series models support

- packages/server/src/controllers/documentstore/index.ts
- packages/server/src/services/documentstore/index.ts
- packages/server/src/utils/buildChatflow.ts
- packages/ui/src/ui-component/cards/FollowUpPromptsCard.jsx
- packages/ui/src/ui-component/extended/FileUpload.jsx
- packages/ui/src/ui-component/extended/OverrideConfig.jsx
- packages/ui/src/ui-component/extended/RateLimit.jsx
- packages/ui/src/ui-component/extended/Security.jsx
- packages/ui/src/views/chatmessage/ChatMessage.jsx
1. Fix: Configuration Not saved properly - Rate Limit & Override Config will overwrite each other
2. Fix: Post Processing Incorrectly escaping newlines and other chars 
3. Fix: Follow on Prompts error while rendering in non-streaming mode
4. NEW: Ability to select filetypes for full file uploads
> changes & fixes for various issues in chatflow config

- packages/ui/src/views/marketplaces/index.jsx
Noticed minor UI issue while exploring Flowise.
Issue:
On the Marketplace page, the label provided to the OutlinedInput component is incorrect, which causes the "Framework" label to overlap with the input border. Additionally, for other Select fields like "Tag" and "Type", there is extra spacing between the label and the border. (Please see the attached screenshot for reference.)
**Before**:
**After**:
> fix: update correct label for InputLabel component

- packages/components/nodes/recordmanager/PostgresRecordManager/PostgresRecordManager.ts
**Problem:**
The `PostgresRecordManager` node experienced two main issues:
1.  **Incorrect Time Handling:** The `getTime()` method used the query `SELECT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)` without aliasing the result column. This caused `res[0].now` to be `undefined` in the subsequent code, leading to a`NaN` value in the database. This `NaN` value was then stored in the `updated_at` column, causing incorrect record tracking, cleanup behavior, and indexing issues.
2.  **Schema Creation Failure on Older PostgreSQL:** The `createSchema()` method uses `gen_random_uuid()` in its `CREATE TABLE` statement. On older PostgreSQL versions (prior to v13), this function is only available via the `pgcrypto` extension. The node did not ensure this extension was enabled, leading to failures when …
> Fix(PostgresRecordManager): Handle time correctly and ensure schema creation

- packages/components/nodes/chatmodels/ChatGoogleVertexAI/ChatGoogleVertexAI.ts
Today, the customModelName field is not optional, despite the message indicating that it should be. This PR makes this field optional.
How it is currently before this PR:
> bugfix: change field to be optional

- packages/components/models.json
Closes #4484 
**Description:**
This PR adds support for two additional models to the ChatMistralAI integration:
These models are part of [Mistral’s officially released lineup](https://mistral.ai/pricing#api-pricing) but were not previously available in the Flowise UI. Adding them expands the model selection and improves support for various use cases relying on these newer offerings.
**Changes:**
- Extended the list of supported model identifiers for ChatMistralAI
**Motivation:**
This change ensures that users can access the latest Mistral models directly within Flowise without requiring manual configuration or backend modifications.
**Testing:**
- Verified model selection and response flow using each newly added model
- Confirmed that existing functionality remains unaffected
Let me know …
> Feature: add missing chat mistral ai models

- packages/server/src/utils/buildAgentflow.ts
This PR updates the variable resolution system in buildAgentflow.ts to support dot notation for accessing nested properties in node outputs. Users can now reference specific nested values using the format nodeId.output.path instead of only accessing the entire output content.
**Examples**
**Before**
{{nodeId}}  // Returns entire output.content or output object
**After**
{{nodeId.output.result.summary}}          // Access nested summary property
{{nodeId.output.metadata.timestamp}} // Access nested timestamp
{{nodeId}}                                                 // Still works - backwards compatible
> Feature: Add dot notation support for nested output variable resolution

- packages/server/src/database/migrations/mariadb/1733752119696-AddSeqNoToDatasetRow.ts
- packages/server/src/database/migrations/mariadb/1744964560174-AddErrorToEvaluationRun.ts
- packages/server/src/enterprise/database/migrations/mariadb/1730519457880-AddSSOColumns.ts
Fixes a MariaDB-specific SQL syntax error during typeorm migration:revert.
When reverting a migration, TypeORM generates queries using double quotes for identifiers, which is invalid in MariaDB. This PR updates the query to use backticks instead.
Before:
```ALTER TABLE "evaluation_run" DROP COLUMN "errors";```
After:
```ALTER TABLE `evaluation_run` DROP COLUMN `errors`;```
Affects only MariaDB users during migration rollback.
> bugfix/Fix SQL syntax error when reverting migration in MariaDB

- packages/ui/src/ui-component/dropdown/AsyncDropdown.jsx
- Adjusted the `Autocomplete` component's width to `90%` when `multiple` is true to prevent clipping of the refresh button.
- Added a tooltip on hover for selected action items to display the **full action name**, especially when it overflows.
- Long action names were causing UI overflow, making the refresh button partially hidden and selected text unreadable.
- Improved UX by making the layout more responsive and enhancing the visibility of selected items.
- This change affects only the `Autocomplete` UI within the affected node and has no side effects on other components.
> fix: Modify the style of the AsyncDropdown component

- packages/components/nodes/agentflow/HTTP/HTTP.ts
- Introduced `sanitizeJsonString` to clean problematic escape sequences and fix common JSON formatting issues.
- Added `parseJsonBody` to attempt parsing JSON directly, with fallback to sanitization if parsing fails, providing clearer error messages for invalid JSON.
- Updated request handling to utilize the new parsing method for JSON and x-www-form-urlencoded body types.
> Bugfix/HTTP Node Body Parsing

- packages/ui/src/views/marketplaces/index.jsx
- Fixed the issue where disabled marketplace tags were barely visible in dark mode.
- Applied custom `sx` styling to override default MUI colors:
- Changed the checkbox icon color to `#888` when disabled.
- Matched the label color to `#888` for consistency.
- The update ensures disabled tags are still visibly distinct without clashing with the overall theme.
---
> Disabled tags were almost invisible — icon and label were too dim.
---
> Disabled tags are now clearly visible using a readable gray color (`#888`).
---
1. Switch to dark mode.
2. Go to the Marketplace view.
3. Trigger a condition where some use case tags become disabled.
4. Verify the disabled tags are now visible and styled appropriately.
---
Fixes #4675
> fix: improve tag visibility in dark mode when disabled (#4675)

- packages/components/nodes/tools/MCP/core.ts
When some of tools in custom MCP server have incorrect schema definition, Flowise failed to load that MCP server with zero error indication.
Linked to Issue #4749 
The root cause is when there is any rejected promise the `Promise.all()` will abort all remaining result and fall silently.
This PR replace `Promise.all()` with `Promise.allSettled()`, this change provides two benefits:
1. even some tools failed to resolve, remaining tools that available in that MCP server is still accessible
2. print errors making it easier to debug for Custom MCP users
> fix(components): promise.all failed silently when loading MCP tools

- packages/components/src/storageUtils.ts
Hi, 
When using local storage by default that folder won't exist (`path.join(getUserHome(), '.flowise', 'storage')`), if you delete an agent - you get an error log because it tries to calculate the size of the storage directory.
This PR ensures that the folder recursively exists if it does not already.
> Init the storagepath

- packages/components/nodes/textsplitters/MarkdownTextSplitter/MarkdownTextSplitter.ts
Description:
Adds configurable header-based splitting to MarkdownTextSplitter component for semantic document
chunking by writing a custom method since its not a native option in langchain.js.
- Dropdown selection for header levels (H1-H6)
- Hierarchical splitting (H2 includes H1 headers)
- Headers preserved with content sections
- Prioritizes semantic boundaries over chunk size
✅ Tested with 23KB real-world markdown document
✅ All splitting scenarios working correctly
✅ Production build successful
- H1: 5 chunks (4,568 chars avg)
- H2: 21 chunks (1,086 chars avg)
- H3: 69 chunks (329 chars avg)
> feat: Add header-based splitting to MarkdownTextSplitter

- packages/components/nodes/tools/MCP/CustomMCP/CustomMCP.ts
- packages/server/src/CachePool.ts
- packages/server/src/services/nodes/index.ts
- Added methods to CachePool for managing MCP toolkit cache.
- Integrated caching logic in CustomMCP to store and retrieve toolkit data based on workspaceId and configuration.
- Updated node service to pass cachePool to CustomMCP for enhanced performance.
> Feat/Implement caching for MCP toolkit in CachePool

- packages/server/src/index.ts
Refactor URL filtering logic in App class
- Introduced a denylist for URLs using the DENYLIST_URLS environment variable.
- Updated the whitelist logic to filter out denylisted URLs, ensuring improved request validation.
> Chore/Add Deny List URLs

- packages/server/src/controllers/chatflows/index.ts
- packages/server/src/routes/chatflows/index.ts
- packages/server/src/services/chatflows/index.ts
- packages/ui/src/api/chatflows.js
This PR removes the `importChatflow` method from "packages/server/src/services/chatflows/index.ts" as it has been replaced by the implementation in "packages/server/src/services/export-import/index.ts".
**Load Chatflow**
**Import Chatflow**
> Chore deprecate importChatflows method

- packages/components/nodes/agentflow/LLM/LLM.ts
This pull request fixes the issue where structuredOutput[key] values of 0 or false are ignored
> Fix: ignored agentflow LLM structuredOutput keys

- packages/components/nodes/tools/MCP/CustomMCP/CustomMCP.ts
- packages/components/nodes/tools/MCP/Supergateway/SupergatewayMCP.ts
- packages/components/nodes/tools/MCP/core.ts
- Implemented a validation function to check for banned commands and dangerous patterns.
- Added checks for potential shell injection attempts in command and arguments.
- Security validation is conditionally enabled based on environment variable CUSTOM_MCP_SECURITY_CHECK.
> Bugfix/Custom MCP Security

- packages/components/nodes/tools/MCP/CustomMCP/CustomMCP.ts
- packages/components/nodes/tools/MCP/Supergateway/SupergatewayMCP.ts
- packages/components/nodes/tools/MCP/core.ts
- packages/ui/src/views/canvas/NodeInputHandler.jsx
- Updated `validateMCPServerSecurity` to only allow whitelisted commands, removing the extensive list of dangerous commands.
- Introduced `validateArgsForLocalFileAccess` to check for potential local file access patterns and null byte injections.
- Updated `Supergateway_MCP` to utilize the new argument validation function.
- Added a warning in `CustomMCP` regarding upcoming changes to Remote MCP support.
> Chore/Custom MCP Validation

- i18n/README-TW.md
This PR improves the Traditional Chinese README (`README-TW.md`) by refining translations and terminology to better fit the zh-TW developer community.
Changes:
- Updated terms such as "環境變量" → "環境變數", "雲" → "雲端平台"
- Improved natural phrasing in multiple sections
- Made the deployment instructions easier to understand for Traditional Chinese users.
Let me know if any adjustments are needed. Happy to revise based on feedback!
> docs: refine Traditional Chinese README (zh-TW)

- packages/components/nodes/agentflow/Agent/Agent.ts
- packages/components/nodes/agentflow/CustomFunction/CustomFunction.ts
- packages/components/nodes/agentflow/ExecuteFlow/ExecuteFlow.ts
- packages/components/nodes/agentflow/Retriever/Retriever.ts
- packages/components/nodes/agentflow/Tool/Tool.ts
When a state update includes the {{ output }} variable, the whole value is replaced by the node output.
I assume this is unintentional, so I've used replaceAll instead.
> Fixes state interpolation when using {{ output }}

- packages/components/src/utils.ts
When converting HTML-wrapped JSON in the stripHTMLFromToolInput with Turndown, square brackets (and underscores) were being escaped (e.g. \[/\]), breaking JSON parsing. 
This adds an update to the existing post-processing step to unescape [_\[\]], restoring the original characters.
**Example**
```
// Before (incorrect)
stripHTMLFromToolInput('<p>{"targets":["https://test.com/"]}</p>')
//   '{"targets":\\["https://test.com/"\\]}'  
// After (fixed)
stripHTMLFromToolInput('<p>{"targets":["https://test.com/"]}</p>')
//   '{"targets":["https://test.com/"]}'
```
> Fix stripHTMLFromToolInput conversion escaping

- packages/components/models.json
This PR adds support for OpenAI's new open-weight GPT-OSS models that are now available on AWS Bedrock.
Pricing is based on https://aws.amazon.com/bedrock/pricing/
only available in us-west-2 region
Tested by configuring MODEL_LIST_CONFIG_JSON to local `models.json`.
No idea why it pretends to be gpt-4, but it works.
> Feat: add gpt oss models to aws bedrock 

- packages/components/src/handler.test.ts
- packages/components/src/handler.ts
This PR adds support for both Self-Hosted & Cloud Phoenix integration. It enables tracing with endpoint URLs that may include space-specific path components. The update also adds validation logic to handle URLs with or without path suffixes, making setup seamless for Phoenix Cloud instances.
**Phoenix Cloud**
**Self-Hosted Phoenix**
> feat: Enable Tracing Support For Self-Hosted & Cloud Phoenix Instance

- packages/server/src/database/migrations/mariadb/1755748356008-AddChatFlowNameIndex.ts
- packages/server/src/database/migrations/mysql/1755748356008-AddChatFlowNameIndex.ts
- packages/server/src/database/migrations/postgres/1755748356008-AddChatFlowNameIndex.ts
- packages/server/src/database/migrations/sqlite/1755748356008-AddChatFlowNameIndex.ts
Refactor index creation for chat_flow name across multiple databases to limit indexed length to 255 characters.
Fix:
```
2025-09-15 15:32:54 [ERROR]: QueryFailedError: index row size 3448 exceeds btree version 4 maximum 2704 for index "IDX_chatflow_name"
at PostgresQueryRunner.query (/usr/src/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.2_mongodb@6.3.0_gcp-metadata@7.0.1_socks@2.8.1__mysql2@3.11._91bb8cebce37e0cf7ba17a39ae30ff6a/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AddChatFlowNameIndex1755748356008.up (/usr/src/packages/server/dist/database/migrations/postgres/1755748356008-AddChatFlowNameIndex.js:9:9)
at async MigrationExecutor.executePendingMigrations …
```
> Bugfix/Create Index Chatflow Name

- packages/components/nodes/chatmodels/ChatGoogleGenerativeAI/FlowiseChatGoogleGenerativeAI.ts
If you disable memory from an agent when using Gemini models, it gets bugged.
`[400 Bad Request] * GenerateContentRequest.contents: contents is not specified`
Converting system messages as user input if memory is disabled will not work this time, since the Gemini will perform very differently without system prompt. The trick would be to inject a placeholder, like 3 dots (...), as chat history when memory is disabled for this model.
> fix: ensure Gemini always receives a non-empty contents array

- packages/components/src/secureZodParser.ts
This PR adds support for using .default() on nested objects and arrays in SecureZodSchemaParser.
It enables parsing and handling of Zod schemas with default values for complex/nested structures, improving compatibility with advanced Zod patterns.
| Simple | Complex |
| --- | --- |
| <img width="2559" height="1265" alt="image" src="https://github.com/user-attachments/assets/b7c67562-e278-4811-b4e6-4d9bb814b71d" /> | <img width="2559" height="1265" alt="image" src="https://github.com/user-attachments/assets/d67fdafb-b6ec-42f6-8d41-622e69c25abe" /> |
> Add support for .default() on nested objects and arrays in SecureZodSchemaParser

- packages/components/nodes/agentflow/HTTP/HTTP.ts
Currently HTTP Node doesn't support the URL to be dynamically set from the variables. 
So, enabled this flag
> Ability to support variable in the URL for HTTP Node.
